// Homepage and interactive-scene copy. Scenes are shared by the product pages,
// so their strings live under `scene.*`.
export default {
  en: {
    meta: {
      home: {
        title: 'Clickt — Your busywork, handled. Your decisions, still yours.',
        desc: 'Clickt brings Teams, Checklist, Builder and Presentation into one workspace, with ClicktAI preparing the work and you approving every change. iPhone, iPad, Mac and Android.',
      },
    },
    home: {
      hero: {
        platforms: 'Apple · Android',
        title: '<span class="ln">Your busywork, <em>handled.</em></span> <span class="ln">Your decisions, <em>still yours.</em></span>',
        lead: 'Clickt brings Teams, Checklist, Builder and Presentation into one connected workspace. ClicktAI prepares the work. You approve every change.',
        note: 'Free to start · Priced in NPR for Nepal',
        scroll: 'Scroll',
        phoneAlt: 'Clickt home screen on iPhone with Teams, Builder and Presentation',
      },
      proof: {
        a: 'chart types in Builder',
        b: 'built-in presentation themes',
        c: 'AI providers, bring your own key',
        d: 'changes applied without your approval',
      },
      ch1: {
        slate: 'Chapter 01',
        name: 'One request',
        title: 'One request. <em>Every</em> workspace.',
        lead: 'Tell ClicktAI what needs to happen. It prepares the work in the right module, and every date lands on a single calendar.',
        teams: { k: 'Teams', h: 'Ownership, out in the open.', b: 'Direct tasks, claimable tasks, decisions and announcements. Each one has an owner and a status the whole team can see.', l: 'Explore Teams' },
        checklist: { k: 'Checklist', h: 'Repeatable work, done the same way.', b: 'Priorities, deadlines and recurring items, with progress that stays visible until the last box is ticked.', l: 'Explore Checklist' },
        builder: { k: 'Builder', h: 'Raw data to a clear answer.', b: 'Import a file, run the analysis, and turn it into charts and finished deliverables you can review.', l: 'Explore Builder' },
        presentation: { k: 'Presentation', h: 'From a brief to an editable deck.', b: 'Generate the slides, restyle with designed themes, preview it, then export to PDF or HTML.', l: 'Explore Presentation' },
        calendar: { k: 'Calendar', h: 'Every deadline, one place.', b: 'Tasks, checklists and reminders from every module sync to a single calendar automatically.', l: 'See it in ClicktAI' },
      },
      ch2: {
        slate: 'Chapter 02',
        name: 'Ownership',
        title: 'Ownership without <em>chasing.</em>',
        lead: 'Give work an owner, or leave it open for the team to claim. Reminders handle the follow-up, so nobody has to ask “is this done yet?”.',
        claimK: 'Claimable task',
        reminderK: 'Reminders that respect the night',
      },
      ch3: {
        slate: 'Chapter 03',
        name: 'Data',
        title: 'From raw data to a <em>decision.</em>',
        lead: 'Import a file, run the analysis, then pick the chart that makes the answer obvious. Twelve chart types, one dataset.',
      },
      ch4: {
        slate: 'Chapter 04',
        name: 'Story',
        title: 'From a brief to a deck that <em>looks</em> designed.',
        lead: 'Describe the story. ClicktAI drafts the slides. You restyle with designed themes, edit anything, then present it or export it.',
      },
      ch5: {
        slate: 'Chapter 05',
        name: 'Trust',
        title: 'Nothing changes until <em>you say so.</em>',
        lead: 'ClicktAI is built to assist the decision, not make it. Every change is previewed first, unsupported requests get a clear no, and unclear ones get a question.',
      },
      devices: {
        kicker: 'Everywhere you work',
        title: 'One workspace, on every <em>screen.</em>',
        lead: 'Clickt runs on iPhone, iPad and Mac, and is in private testing on Android. Sign in once and your work follows you.',
        apple: 'Apple',
        phone: 'Phone',
        tablet: 'Tablet',
        desktop: 'Laptop & desktop',
        iphone: 'iPhone',
        ipad: 'iPad',
        mac: 'Mac',
        android: 'Android',
        iphoneAlt: 'Clickt Teams on iPhone',
        ipadAlt: 'Clickt on iPad',
        macAlt: 'Clickt Builder on Mac',
        androidAlt: 'Clickt on Android',
        androidNote: 'Android is in invite-only testing on Google Play.',
      },
      nepal: {
        kicker: 'Made in Kathmandu',
        title: 'Built for the way organisations <em>actually</em> work.',
        lead: 'Clickt sits beside the systems you already run, from school-management software to core banking, and makes the work around them clear.',
        price: 'Free to start. Business is priced in NPR for organisations in Nepal.',
        priceCta: 'See plans',
        all: 'All solutions',
      },
      custom: {
        kicker: 'Click T',
        title: 'Need something built <em>specifically</em> for your organisation?',
        body: 'Click T builds custom software around how your organisation actually works: websites, mobile apps, internal workflow systems, data platforms, integrations and AI-enabled tools, for organisations in Nepal and abroad.',
        existing: 'Already using an ERP, CRM, MIS or booking platform? We do not need to replace what works. We build the missing workflow, integration or application around it.',
        cta: 'Discuss a project',
        work: 'See our work',
      },
      founder: {
        title: 'A note from the founder',
        by: 'Aaryan Jha, Founder, Click T Pvt. Ltd.',
      },
      faq: {
        title: 'Questions, <em>answered.</em>',
        q1: 'Is Clickt free?',
        a1: 'Yes. Free includes Teams, Checklist, Builder, Presentation and Calendar, and you connect your own AI provider key for ClicktAI. Business adds a company workspace, admin controls and Clickt-provided AI for teams.',
        q2: 'Which devices does it run on?',
        a2: 'iPhone, iPad and Mac through the App Store. Android is in invite-only testing on Google Play, so request access first.',
        q3: 'Can ClicktAI change my work without asking?',
        a3: 'No. Every write action shows a preview first and waits for your approval. Nothing is applied until you say so.',
        q4: 'Do I need my own AI account?',
        a4: 'On Free, yes. You connect an OpenAI, Anthropic, Google Gemini or NVIDIA key, and usage is billed to your own account. On Business, your admin can assign Clickt-provided AI to the people who need it.',
        q5: 'Does Clickt replace our existing software?',
        a5: 'No. It is the coordination layer beside your ERP, school-management system, core banking or spreadsheets. If you need a tailored integration, Click T can build it.',
      },
      final: {
        title: 'Hand off the busywork. <em>Keep</em> the decisions.',
        lead: 'Start with one project. Clickt does the setup, you make the calls.',
      },
    },
    scene: {
      approve: {
        you: 'You',
        request: 'Plan our Dashain sale launch. Assign the team, build the checklist, chart last year’s sales and draft the leadership update.',
        thinking: 'Preparing a proposal…',
        draft: 'Draft',
        head: 'Proposed work',
        teams: 'Assign 6 launch tasks with owners and deadlines',
        checklist: 'Create the store-opening checklist',
        builder: 'Chart last year’s sales by city',
        presentation: 'Draft an 8-slide leadership update',
        note: 'Nothing is applied until you approve.',
        button: 'Approve & apply',
        applied: 'Applied',
        receipt: '4 changes applied',
        receiptN: '{n} changes applied',
        receiptSub: 'Receipt saved · just now',
        reset: 'Watch again',
        status: { ready: 'Ready', prep: 'Preparing', review: 'Waiting for your approval', done: 'Done' },
      },
      claim: {
        task: 'Print festival banners',
        sub: 'Claimable · due Friday, 5:00 PM',
        open: 'Open',
        claimed: 'Claimed',
        done: 'Done',
        claim: 'Claim',
        race: 'Both tap Claim at once',
        winner: '{name} got it.',
        already: 'Already claimed by {name}',
        n1: 'Sam',
        n2: 'Alex',
        i1: 'S',
        i2: 'A',
        server: 'When two people claim at the same moment, the server picks exactly one winner.',
        again: 'Reset',
        complete: 'Mark done',
      },
      reminder: {
        due: 'Due at',
        pre: '15 min before',
        atDue: 'Due',
        follow: 'Every 3 h while open',
        quiet: 'Quiet hours 22:00–08:00',
        digest: '08:00 digest',
        deferred: 'Deferred to the digest',
        done: 'Mark as done',
        undo: 'Reopen',
        stopped: 'Marked done. Reminders stop immediately.',
        summary: 'A reminder 15 minutes before it is due, then every 3 hours while it is still open. Follow-ups wait out quiet hours and arrive in one 08:00 digest.',
      },
      checklist: {
        title: 'Weekly store opening',
        recurring: 'Repeats every Monday',
        i1: 'Unlock and disarm the alarm',
        i2: 'Count the till float',
        i3: 'Check stock on the front shelves',
        i4: 'Switch on displays and music',
        progress: '{n} of {total} done',
        next: 'Done. Back next Monday.',
        reset: 'Start the next week',
      },
      chart: {
        dataset: 'Q3 sales by city',
        city: 'City',
        sales: 'Sales (NPR lakh)',
        kathmandu: 'Kathmandu',
        pokhara: 'Pokhara',
        lalitpur: 'Lalitpur',
        biratnagar: 'Biratnagar',
        butwal: 'Butwal',
        bar: 'Bar',
        line: 'Line',
        area: 'Area',
        donut: 'Donut',
        scatter: 'Scatter',
        heat: 'Heatmap',
        more: '+6 more',
        types: '12 chart types',
        export: 'Export as PNG, DOC or PPT',
        pick: 'Choose a chart',
      },
      deck: {
        title: 'Q3 sales review',
        sub: 'Prepared for leadership',
        k1: 'NPR 4.2 Cr',
        k1l: 'Q3 sales',
        k2: '+18%',
        k2l: 'vs Q2',
        k3: 'Kathmandu',
        k3l: 'Top city',
        spotlight: 'Spotlight',
        story: 'Guided Story',
        editorial: 'Editorial',
        themes: '23 built-in themes',
        export: 'Present, or export to PDF or HTML',
        pick: 'Choose a design',
      },
      trust: {
        tabPreview: 'Preview first',
        tabRefusal: 'A clear no',
        tabAsk: 'It asks',
        previewAsk: 'Add a task for Sam: order the banners.',
        previewCard: 'Write preview',
        pr1: 'Create task in Launch Team',
        pr2: 'Owner: Sam · Due Friday',
        pr3: 'Notify Sam',
        previewApprove: 'Approve',
        previewCancel: 'Cancel',
        previewReceipt: 'Applied. Receipt saved.',
        refusalAsk: 'Book me a flight to Pokhara.',
        refusalSay: 'I can’t book flights.',
        refusalWhy: 'ClicktAI only works inside Teams, Checklist, Builder and Presentation.',
        refusalAlt: 'Here is what I can do:',
        refusalA1: 'Create a trip checklist',
        refusalA2: 'Add a travel task to your team',
        refusalA3: 'Draft a trip briefing deck',
        refusalNext: 'Want me to start one of these?',
        askAsk: 'Assign the venue task to Sam.',
        askSay: 'Two teams are called “Launch”. Which one do you mean?',
        askA: 'Launch · Marketing',
        askB: 'Launch · Product',
        askDone: 'Got it. Preparing a preview for {team}…',
        hint: 'Try it — tap through.',
      },
      key: {
        title: 'Your AI. Your key. Your bill.',
        lead: 'Connect the provider you already use. ClicktAI works with your own key, and usage is billed to your own account.',
        openai: 'OpenAI',
        anthropic: 'Anthropic',
        gemini: 'Google Gemini',
        nvidia: 'NVIDIA',
        f1: 'Kept in your device’s secure storage',
        f2: 'Sent only to that provider',
        f3: 'Billed to your own account',
        placeholder: 'Paste your API key',
      },
    },
  },
  ne: {
    meta: {
      home: {
        title: 'Clickt — तपाईंको झन्झटिलो काम सम्हालिन्छ। निर्णय, तपाईंकै।',
        desc: 'Clickt ले Teams, Checklist, Builder र Presentation एउटै कार्यक्षेत्रमा ल्याउँछ। ClicktAI ले काम तयार गर्छ, हरेक परिवर्तन तपाईंले स्वीकृत गर्नुहुन्छ। iPhone, iPad, Mac र Android।',
      },
    },
    home: {
      hero: {
        platforms: 'Apple · Android',
        title: '<span class="ln">तपाईंको दोहोरिने काम, <em>सम्हालियो।</em></span> <span class="ln">तपाईंको निर्णय, <em>अझै तपाईंकै।</em></span>',
        lead: 'Clickt ले Teams, Checklist, Builder र Presentation लाई एउटै जोडिएको कार्यक्षेत्रमा ल्याउँछ। ClicktAI ले काम तयार गर्छ। हरेक परिवर्तन तपाईंले स्वीकृत गर्नुहुन्छ।',
        note: 'निःशुल्क सुरु · नेपालका लागि NPR मा मूल्य',
        scroll: 'तल स्क्रोल गर्नुहोस्',
        phoneAlt: 'Teams, Builder र Presentation सहितको iPhone मा Clickt को गृहपृष्ठ',
      },
      proof: {
        a: 'Builder मा चार्ट प्रकार',
        b: 'समावेश गरिएका प्रस्तुति थिम',
        c: 'AI प्रदायक, आफ्नै की जोड्नुहोस्',
        d: 'तपाईंको स्वीकृतिबिना लागू परिवर्तन',
      },
      ch1: {
        slate: 'अध्याय ०१',
        name: 'एउटा अनुरोध',
        title: 'एउटा अनुरोध। <em>हरेक</em> कार्यक्षेत्र।',
        lead: 'के हुनुपर्छ भन्ने ClicktAI लाई भन्नुहोस्। उसले सही मोड्युलमा काम तयार गर्छ, र हरेक मिति एउटै पात्रोमा आइपुग्छ।',
        teams: { k: 'Teams', h: 'जिम्मेवारी, खुला रूपमा।', b: 'सिधा कार्य, दाबी गर्न मिल्ने कार्य, निर्णय र घोषणा। हरेकको जिम्मेवार व्यक्ति र अवस्था सबै टोलीले देख्न सक्छ।', l: 'Teams हेर्नुहोस्' },
        checklist: { k: 'Checklist', h: 'दोहोरिने काम, उही तरिकाले।', b: 'प्राथमिकता, म्याद र दोहोरिने वस्तु, अन्तिम बाकस टिक नलागेसम्म देखिने प्रगतिसहित।', l: 'Checklist हेर्नुहोस्' },
        builder: { k: 'Builder', h: 'कच्चा डेटाबाट स्पष्ट उत्तर।', b: 'फाइल आयात गर्नुहोस्, विश्लेषण चलाउनुहोस्, र समीक्षा गर्न मिल्ने चार्ट तथा तयार सामग्रीमा बदल्नुहोस्।', l: 'Builder हेर्नुहोस्' },
        presentation: { k: 'Presentation', h: 'ब्रिफबाट सम्पादन गर्न मिल्ने डेक।', b: 'स्लाइड बनाउनुहोस्, डिजाइन गरिएका थिमले नयाँ रूप दिनुहोस्, पूर्वावलोकन गर्नुहोस्, अनि PDF वा HTML मा निर्यात गर्नुहोस्।', l: 'Presentation हेर्नुहोस्' },
        calendar: { k: 'पात्रो', h: 'हरेक म्याद, एउटै ठाउँमा।', b: 'हरेक मोड्युलका कार्य, चेकलिस्ट र रिमाइन्डर आफैँ एउटै पात्रोमा सिंक हुन्छन्।', l: 'ClicktAI मा हेर्नुहोस्' },
      },
      ch2: {
        slate: 'अध्याय ०२',
        name: 'जिम्मेवारी',
        title: 'पछि लाग्नु नपर्ने <em>जिम्मेवारी।</em>',
        lead: 'कामलाई जिम्मेवार व्यक्ति दिनुहोस्, वा टोलीले दाबी गर्न खुला छोड्नुहोस्। फलोअप रिमाइन्डरले गर्छ, त्यसैले “यो सकियो?” भनेर कसैले सोध्नु पर्दैन।',
        claimK: 'दाबी गर्न मिल्ने कार्य',
        reminderK: 'रातको ख्याल गर्ने रिमाइन्डर',
      },
      ch3: {
        slate: 'अध्याय ०३',
        name: 'डेटा',
        title: 'कच्चा डेटाबाट <em>निर्णयसम्म।</em>',
        lead: 'फाइल आयात गर्नुहोस्, विश्लेषण चलाउनुहोस्, अनि उत्तर स्पष्ट देखाउने चार्ट रोज्नुहोस्। बाह्र चार्ट प्रकार, एउटै डेटासेट।',
      },
      ch4: {
        slate: 'अध्याय ०४',
        name: 'कथा',
        title: 'ब्रिफबाट <em>राम्रोसँग डिजाइन</em> गरिएको डेकसम्म।',
        lead: 'कथा वर्णन गर्नुहोस्। ClicktAI ले स्लाइड बनाउँछ। तपाईं डिजाइन गरिएका थिमले नयाँ रूप दिनुहुन्छ, जे पनि सम्पादन गर्नुहुन्छ, अनि प्रस्तुत वा निर्यात गर्नुहुन्छ।',
      },
      ch5: {
        slate: 'अध्याय ०५',
        name: 'भरोसा',
        title: 'तपाईंले नभनेसम्म <em>केही बदलिँदैन।</em>',
        lead: 'ClicktAI निर्णयमा सहयोग गर्न बनेको हो, निर्णय लिन होइन। हरेक परिवर्तन पहिले पूर्वावलोकनमा देखिन्छ, असमर्थित अनुरोधले स्पष्ट “होइन” पाउँछ, र अस्पष्टले प्रश्न।',
      },
      devices: {
        kicker: 'तपाईं काम गर्ने जुनसुकै ठाउँमा',
        title: 'एउटै कार्यक्षेत्र, हरेक <em>स्क्रिनमा।</em>',
        lead: 'Clickt iPhone, iPad र Mac मा चल्छ, र Android मा निजी परीक्षणमा छ। एक पटक साइन इन गर्नुहोस्, तपाईंको काम तपाईंसँगै जान्छ।',
        apple: 'Apple',
        phone: 'Phone',
        tablet: 'Tablet',
        desktop: 'Laptop & desktop',
        apple: 'Apple',
        phone: 'फोन',
        tablet: 'ट्याब्लेट',
        desktop: 'ल्यापटप र डेस्कटप',
        iphone: 'iPhone',
        ipad: 'iPad',
        mac: 'Mac',
        android: 'Android',
        iphoneAlt: 'iPhone मा Clickt Teams',
        ipadAlt: 'iPad मा Clickt',
        macAlt: 'Mac मा Clickt Builder',
        androidAlt: 'Android मा Clickt',
        androidNote: 'Android Google Play मा निमन्त्रणा-आधारित परीक्षणमा छ।',
      },
      nepal: {
        kicker: 'काठमाडौंमा निर्मित',
        title: 'संस्थाहरू <em>वास्तवमा</em> काम गर्ने तरिका अनुसार बनाइएको।',
        lead: 'विद्यालय-व्यवस्थापन सफ्टवेयरदेखि कोर बैंकिङसम्म, तपाईंले चलाइरहेका प्रणालीको छेउमा Clickt बस्छ र वरिपरिको काम स्पष्ट बनाउँछ।',
        price: 'निःशुल्क सुरु गर्नुहोस्। नेपालका संस्थाका लागि बिजनेस NPR मा मूल्य तोकिएको छ।',
        priceCta: 'योजना हेर्नुहोस्',
        all: 'सबै समाधान',
      },
      custom: {
        kicker: 'Click T',
        title: 'तपाईंको संस्थाका लागि <em>विशेष रूपमा</em> केही बनाउनुपर्ने छ?',
        body: 'Click T ले तपाईंको संस्थाले वास्तवमा काम गर्ने तरिका वरिपरि कस्टम सफ्टवेयर बनाउँछ: वेबसाइट, मोबाइल एप, आन्तरिक कार्यप्रवाह प्रणाली, डेटा प्लेटफर्म, इन्टिग्रेसन र AI-सक्षम उपकरण, नेपाल र विदेशका संस्थाहरूका लागि।',
        existing: 'पहिल्यै ERP, CRM, MIS वा बुकिङ प्लेटफर्म प्रयोग गर्दै हुनुहुन्छ? चलिरहेको कुरा फेर्नु पर्दैन। हामी त्यसको वरिपरि छुटेको कार्यप्रवाह, इन्टिग्रेसन वा एप बनाउँछौं।',
        cta: 'परियोजनाबारे छलफल गर्नुहोस्',
        work: 'हाम्रो काम हेर्नुहोस्',
      },
      founder: {
        title: 'संस्थापकको एक नोट',
        by: 'आर्यन झा, संस्थापक, Click T Pvt. Ltd.',
      },
      faq: {
        title: 'प्रश्नहरू, <em>उत्तरसहित।</em>',
        q1: 'के Clickt निःशुल्क हो?',
        a1: 'हो। निःशुल्क योजनामा Teams, Checklist, Builder, Presentation र पात्रो समावेश छन्, र ClicktAI का लागि तपाईंले आफ्नै AI प्रदायकको की जोड्नुहुन्छ। बिजनेसले कम्पनी कार्यक्षेत्र, एडमिन नियन्त्रण र टोलीका लागि Clickt-प्रदत्त AI थप्छ।',
        q2: 'यो कुन उपकरणमा चल्छ?',
        a2: 'App Store मार्फत iPhone, iPad र Mac मा। Android Google Play मा निमन्त्रणा-आधारित परीक्षणमा छ, त्यसैले पहिले पहुँच अनुरोध गर्नुहोस्।',
        q3: 'के ClicktAI ले सोधेर नसोधी मेरो काम बदल्न सक्छ?',
        a3: 'सक्दैन। हरेक लेख्ने कार्यले पहिले पूर्वावलोकन देखाउँछ र तपाईंको स्वीकृतिको प्रतीक्षा गर्छ। तपाईंले नभनेसम्म केही लागू हुँदैन।',
        q4: 'के मलाई आफ्नै AI खाता चाहिन्छ?',
        a4: 'निःशुल्क योजनामा चाहिन्छ। तपाईंले OpenAI, Anthropic, Google Gemini वा NVIDIA को की जोड्नुहुन्छ, र प्रयोग शुल्क तपाईंकै खातामा लाग्छ। बिजनेसमा, तपाईंको एडमिनले आवश्यक व्यक्तिहरूलाई Clickt-प्रदत्त AI तोक्न सक्छ।',
        q5: 'के Clickt ले हाम्रो वर्तमान सफ्टवेयर प्रतिस्थापन गर्छ?',
        a5: 'गर्दैन। यो तपाईंको ERP, विद्यालय-व्यवस्थापन प्रणाली, कोर बैंकिङ वा स्प्रेडसिटको छेउको समन्वय तह हो। अनुकूल इन्टिग्रेसन चाहिएमा Click T ले बनाइदिन सक्छ।',
      },
      final: {
        title: 'झन्झटिलो काम सुम्पनुहोस्। निर्णय <em>आफैँ</em> लिनुहोस्।',
        lead: 'एउटा परियोजनाबाट सुरु गर्नुहोस्। सेटअप Clickt ले गर्छ, निर्णय तपाईंले लिनुहुन्छ।',
      },
    },
    scene: {
      approve: {
        you: 'तपाईं',
        request: 'हाम्रो दसैँ सेल लन्च योजना बनाउनुहोस्। टोलीलाई काम तोक्नुहोस्, चेकलिस्ट बनाउनुहोस्, गत वर्षको बिक्रीको चार्ट बनाउनुहोस् र नेतृत्वका लागि अपडेट ड्राफ्ट गर्नुहोस्।',
        thinking: 'प्रस्ताव तयार गर्दै…',
        draft: 'ड्राफ्ट',
        head: 'प्रस्तावित काम',
        teams: 'जिम्मेवार व्यक्ति र म्यादसहित ६ लन्च कार्य तोक्नुहोस्',
        checklist: 'पसल खोल्ने चेकलिस्ट बनाउनुहोस्',
        builder: 'गत वर्षको बिक्री सहर अनुसार चार्टमा देखाउनुहोस्',
        presentation: '८ स्लाइडको नेतृत्व अपडेट ड्राफ्ट गर्नुहोस्',
        note: 'तपाईंले स्वीकृत नगरेसम्म केही लागू हुँदैन।',
        button: 'स्वीकृत गरी लागू गर्नुहोस्',
        applied: 'लागू भयो',
        receipt: '४ परिवर्तन लागू भए',
        receiptN: '{n} परिवर्तन लागू भए',
        receiptSub: 'रसिद सुरक्षित · भर्खरै',
        reset: 'फेरि हेर्नुहोस्',
        status: { ready: 'तयार', prep: 'तयार गर्दै', review: 'तपाईंको स्वीकृतिको प्रतीक्षा', done: 'सकियो' },
      },
      claim: {
        task: 'चाडपर्वका ब्यानर छाप्नुहोस्',
        sub: 'दाबी गर्न मिल्ने · शुक्रबार, ५:०० बजे म्याद',
        open: 'खुला',
        claimed: 'दाबी गरियो',
        done: 'सकियो',
        claim: 'दाबी गर्नुहोस्',
        race: 'दुवैले एकैचोटि दाबी थिच्छन्',
        winner: '{name} ले पायो।',
        already: '{name} ले पहिल्यै दाबी गरिसक्नुभयो',
        n1: 'सैम',
        n2: 'एलेक्स',
        i1: 'सै',
        i2: 'ए',
        server: 'दुई जनाले एकैछिन दाबी गर्दा, सर्भरले ठ्याक्कै एक जना विजेता छान्छ।',
        again: 'रिसेट',
        complete: 'सकियो भनी चिह्न लगाउनुहोस्',
      },
      reminder: {
        due: 'म्याद',
        pre: '१५ मिनेट अघि',
        atDue: 'म्याद',
        follow: 'खुला रहँदासम्म हरेक ३ घण्टामा',
        quiet: 'शान्त समय २२:००–०८:००',
        digest: '०८:०० डाइजेस्ट',
        deferred: 'डाइजेस्टसम्म स्थगित',
        done: 'सकियो भनी चिह्न लगाउनुहोस्',
        undo: 'फेरि खोल्नुहोस्',
        stopped: 'सकियो भनी चिह्न लगाइयो। रिमाइन्डर तुरुन्तै रोकिन्छ।',
        summary: 'म्यादभन्दा १५ मिनेट अघि रिमाइन्डर, त्यसपछि खुला रहँदासम्म हरेक ३ घण्टामा। फलोअपले शान्त समयसम्म पर्खन्छ र ०८:०० को एउटै डाइजेस्टमा आइपुग्छ।',
      },
      checklist: {
        title: 'साप्ताहिक पसल खोल्ने प्रक्रिया',
        recurring: 'हरेक सोमबार दोहोरिन्छ',
        i1: 'ताला खोल्नुहोस् र अलार्म बन्द गर्नुहोस्',
        i2: 'दराजको नगद गन्नुहोस्',
        i3: 'अगाडिको र्‍याकमा सामान जाँच्नुहोस्',
        i4: 'डिस्प्ले र सङ्गीत चलाउनुहोस्',
        progress: '{total} मध्ये {n} सकियो',
        next: 'सकियो। अर्को सोमबार फेरि आउँछ।',
        reset: 'अर्को हप्ता सुरु गर्नुहोस्',
      },
      chart: {
        dataset: 'तेस्रो त्रैमासिक बिक्री, सहर अनुसार',
        city: 'सहर',
        sales: 'बिक्री (रु. लाख)',
        kathmandu: 'काठमाडौं',
        pokhara: 'पोखरा',
        lalitpur: 'ललितपुर',
        biratnagar: 'विराटनगर',
        butwal: 'बुटवल',
        bar: 'बार',
        line: 'लाइन',
        area: 'एरिया',
        donut: 'डोनट',
        scatter: 'स्क्याटर',
        heat: 'हिटम्याप',
        more: '+६ थप',
        types: '१२ चार्ट प्रकार',
        export: 'PNG, DOC वा PPT मा निर्यात गर्नुहोस्',
        pick: 'चार्ट रोज्नुहोस्',
      },
      deck: {
        title: 'तेस्रो त्रैमासिक बिक्री समीक्षा',
        sub: 'नेतृत्वका लागि तयार पारिएको',
        k1: 'रु. ४.२ करोड',
        k1l: 'त्रैमासिक बिक्री',
        k2: '+१८%',
        k2l: 'अघिल्लो त्रैमासभन्दा',
        k3: 'काठमाडौं',
        k3l: 'शीर्ष सहर',
        spotlight: 'Spotlight',
        story: 'Guided Story',
        editorial: 'Editorial',
        themes: '२३ समावेश गरिएका थिम',
        export: 'प्रस्तुत गर्नुहोस्, वा PDF अथवा HTML मा निर्यात गर्नुहोस्',
        pick: 'डिजाइन रोज्नुहोस्',
      },
      trust: {
        tabPreview: 'पहिले पूर्वावलोकन',
        tabRefusal: 'स्पष्ट “होइन”',
        tabAsk: 'सोध्छ',
        previewAsk: 'सैमका लागि कार्य थप्नुहोस्: ब्यानर अर्डर गर्ने।',
        previewCard: 'लेख्ने पूर्वावलोकन',
        pr1: 'लन्च टोलीमा कार्य बनाउनुहोस्',
        pr2: 'जिम्मेवार: सैम · शुक्रबार म्याद',
        pr3: 'सैमलाई सूचित गर्नुहोस्',
        previewApprove: 'स्वीकृत गर्नुहोस्',
        previewCancel: 'रद्द गर्नुहोस्',
        previewReceipt: 'लागू भयो। रसिद सुरक्षित।',
        refusalAsk: 'मलाई पोखराको फ्लाइट बुक गरिदेऊ।',
        refusalSay: 'म फ्लाइट बुक गर्न सक्दिनँ।',
        refusalWhy: 'ClicktAI ले Teams, Checklist, Builder र Presentation भित्र मात्र काम गर्छ।',
        refusalAlt: 'म यी गर्न सक्छु:',
        refusalA1: 'यात्राको चेकलिस्ट बनाउने',
        refusalA2: 'तपाईंको टोलीमा यात्रा कार्य थप्ने',
        refusalA3: 'यात्रा ब्रिफिङ डेक ड्राफ्ट गर्ने',
        refusalNext: 'यीमध्ये कुनै एक सुरु गरूँ?',
        askAsk: 'भेन्यु कार्य सैमलाई तोक्नुहोस्।',
        askSay: '“Launch” नाम भएका दुई टोली छन्। तपाईंको मतलब कुन हो?',
        askA: 'Launch · मार्केटिङ',
        askB: 'Launch · प्रोडक्ट',
        askDone: 'बुझेँ। {team} का लागि पूर्वावलोकन तयार गर्दै…',
        hint: 'आफैँ थिचेर हेर्नुहोस्।',
      },
      key: {
        title: 'तपाईंको AI। तपाईंको की। तपाईंको बिल।',
        lead: 'तपाईंले पहिल्यै प्रयोग गरिरहेको प्रदायक जोड्नुहोस्। ClicktAI तपाईंकै की सँग काम गर्छ, र प्रयोग शुल्क तपाईंकै खातामा लाग्छ।',
        openai: 'OpenAI',
        anthropic: 'Anthropic',
        gemini: 'Google Gemini',
        nvidia: 'NVIDIA',
        f1: 'तपाईंको उपकरणको सुरक्षित भण्डारणमा राखिन्छ',
        f2: 'त्यही प्रदायकलाई मात्र पठाइन्छ',
        f3: 'तपाईंकै खातामा शुल्क लाग्छ',
        placeholder: 'आफ्नो API की टाँस्नुहोस्',
      },
    },
  },
};
