// <title> and meta description for every page (English + Nepali).
export default {
  en: { meta: {
      'teams': { title: 'Teams — Clear ownership for shared work | Clickt', desc: 'Bring team membership, direct and claimable tasks, decisions, announcements, ownership and status into one Clickt workspace.' },
      'checklist': { title: 'Checklist — Recurring work people can finish | Clickt', desc: 'Make personal and team work easier to see, prioritise and complete, with deadlines, recurrence, progress and reminders that stop when it is done.' },
      'builder': { title: 'Builder — From dataset to decision | Clickt', desc: 'Import a dataset, run the analysis, choose from 12 chart types and export a finished deliverable as PNG, DOC or PPT, or send it into a presentation.' },
      'presentation': { title: 'Presentation — Make the next decision easier to see | Clickt', desc: 'Create, style, preview and export editable decks with 23 built-in themes, then share as an interactive HTML deck or PDF.' },
      'clicktai': { title: 'ClicktAI — Reviewable AI for real work | Clickt', desc: 'ClicktAI prepares work across Teams, Checklist, Builder and Presentation. You review every proposal before anything changes, and you bring your own AI key.' },
      'pricing': { title: 'Pricing — Free to start, priced in NPR for Nepal | Clickt', desc: 'Clickt is free to start. Business adds a company workspace, administration and Clickt-provided AI, priced in NPR for organisations in Nepal and USD elsewhere.' },
      'solutions': { title: 'Solutions — One connected workflow for your team | Clickt', desc: 'Clickt gives schools, healthcare, banks, NGOs, hotels, restaurants and construction teams one connected workflow beside the systems they already run.' },
      'services': { title: 'Services — Custom software built around your organisation | Click T', desc: 'Click T designs and builds custom software, web and mobile apps, data systems, integrations and AI-enabled tools for organisations in Nepal and abroad.' },
      'about': { title: 'About Click T — Software built from Kathmandu', desc: 'Click T builds Clickt and custom software that makes organisational work clearer.' },
      'contact': { title: 'Contact — Talk to Click T', desc: 'Reach Click T at clickt@click-t.com for Clickt support, custom software projects and pricing.' },
      'support': { title: 'Support — Get unstuck quickly | Clickt', desc: 'Quick fixes for common Clickt issues, plus how to reach the support desk.' },
      'security': { title: 'Security & Trust — For IT and procurement | Click T', desc: 'Straight answers on how Clickt handles data, access, AI providers and incidents, written for IT and procurement review.' },
      'android': { title: 'Clickt for Android — Private test on Google Play', desc: 'Clickt for Android is in invite-only testing on Google Play. Preview the Android screens and request access.' },
      'privacy': { title: 'Privacy Statement | Clickt', desc: 'What Clickt collects, why, and what you can do about it.' },
      'terms': { title: 'Terms of Service | Clickt', desc: 'The terms that apply when you use Clickt.' },
      'user-guide': { title: 'User Guide — Get the most out of Clickt', desc: 'How each Clickt module works and why it saves you time, with quick-start paths and troubleshooting.' },
      'pitch-deck': { title: 'Clickt — Business pitch deck', desc: 'The Clickt business pitch deck.' },
      'not-found': { title: 'Page not found | Clickt', desc: 'That page has moved or does not exist.' },
      'solutions-schools': { title: 'Clickt for Schools — Coordinate the work around school life', desc: 'Assign, follow up and report the exam-week, event and department work that sits beside your school-management system.' },
      'solutions-healthcare': { title: 'Clickt for Healthcare — Non-clinical coordination', desc: 'Coordinate maintenance, checks and shift handoffs beside your clinical and hospital systems.' },
      'solutions-banks': { title: 'Clickt for Banks — Branch readiness and follow-up', desc: 'Coordinate branch-readiness, follow-ups and management updates around your core banking system.' },
      'solutions-ngos': { title: 'Clickt for NGOs — Field follow-up and reporting', desc: 'Coordinate field follow-up, programme activities and reporting alongside donor and M&E systems.' },
      'solutions-hotels': { title: 'Clickt for Hotels — Service recovery and handoffs', desc: 'Coordinate service recovery, facilities and shift handoffs beside your PMS and booking systems.' },
      'solutions-restaurants': { title: 'Clickt for Restaurants — Opening, service and closing routines', desc: 'Coordinate opening, service and closing routines alongside your POS and inventory systems.' },
      'solutions-construction': { title: 'Clickt for Construction & Real Estate — Site follow-up', desc: 'Coordinate site follow-up, snag resolution and procurement alongside project and accounting systems.' },
  } },
  ne: { meta: {
      'teams': { title: 'Teams — साझा कामका लागि स्पष्ट जिम्मेवारी | Clickt', desc: 'टोली सदस्यता, सिधा र दाबी गर्न मिल्ने कार्य, निर्णय, घोषणा, जिम्मेवारी र अवस्थालाई एउटै Clickt कार्यक्षेत्रमा ल्याउनुहोस्।' },
      'checklist': { title: 'Checklist — मानिसले पूरा गर्न सक्ने दोहोरिने काम | Clickt', desc: 'म्याद, दोहोरिने क्रम, प्रगति र सकिएपछि रोकिने रिमाइन्डरसहित व्यक्तिगत र टोलीको काम हेर्न, प्राथमिकता दिन र पूरा गर्न सजिलो बनाउनुहोस्।' },
      'builder': { title: 'Builder — डेटासेटबाट निर्णयसम्म | Clickt', desc: 'डेटासेट आयात गर्नुहोस्, विश्लेषण चलाउनुहोस्, १२ चार्ट प्रकारबाट रोज्नुहोस्, र तयार सामग्री PNG, DOC वा PPT मा निर्यात गर्नुहोस् वा प्रस्तुतिमा पठाउनुहोस्।' },
      'presentation': { title: 'Presentation — अर्को निर्णय देख्न सजिलो बनाउनुहोस् | Clickt', desc: '२३ समावेश गरिएका थिमसहित सम्पादन गर्न मिल्ने डेक बनाउनुहोस्, रूप दिनुहोस्, पूर्वावलोकन गर्नुहोस् र निर्यात गर्नुहोस्।' },
      'clicktai': { title: 'ClicktAI — वास्तविक कामका लागि समीक्षायोग्य AI | Clickt', desc: 'ClicktAI ले Teams, Checklist, Builder र Presentation भरि काम तयार गर्छ। केही बदलिनुअघि हरेक प्रस्ताव तपाईंले समीक्षा गर्नुहुन्छ, र आफ्नै AI की ल्याउनुहुन्छ।' },
      'pricing': { title: 'मूल्य — निःशुल्क सुरु, नेपालका लागि NPR मा | Clickt', desc: 'Clickt निःशुल्क सुरु गर्न सकिन्छ। बिजनेसले कम्पनी कार्यक्षेत्र, प्रशासन र Clickt-प्रदत्त AI थप्छ, नेपालका संस्थाका लागि NPR मा र अन्यत्र USD मा।' },
      'solutions': { title: 'समाधान — तपाईंको टोलीका लागि एउटै जोडिएको कार्यप्रवाह | Clickt', desc: 'विद्यालय, स्वास्थ्य सेवा, बैंक, NGO, होटल, रेस्टुरेन्ट र निर्माण टोलीका लागि तिनले चलाइरहेका प्रणालीको छेउमा एउटै जोडिएको कार्यप्रवाह।' },
      'services': { title: 'सेवा — तपाईंको संस्था वरिपरि बनाइएको कस्टम सफ्टवेयर | Click T', desc: 'Click T ले नेपाल र विदेशका संस्थाहरूका लागि कस्टम सफ्टवेयर, वेब र मोबाइल एप, डेटा प्रणाली, इन्टिग्रेसन र AI-सक्षम उपकरण बनाउँछ।' },
      'about': { title: 'Click T बारे — काठमाडौंबाट बनाइएको सफ्टवेयर', desc: 'Click T ले Clickt र संस्थागत काम स्पष्ट बनाउने कस्टम सफ्टवेयर बनाउँछ।' },
      'contact': { title: 'सम्पर्क — Click T सँग कुरा गर्नुहोस्', desc: 'Clickt सहायता, कस्टम सफ्टवेयर परियोजना र मूल्यका लागि clickt@click-t.com मा Click T लाई सम्पर्क गर्नुहोस्।' },
      'support': { title: 'सहायता — छिट्टै समस्या समाधान गर्नुहोस् | Clickt', desc: 'सामान्य Clickt समस्याका छिटा समाधान, र सहायता डेस्कमा कसरी पुग्ने।' },
      'security': { title: 'सुरक्षा र भरोसा — IT र खरिद टोलीका लागि | Click T', desc: 'Clickt ले डेटा, पहुँच, AI प्रदायक र घटनाहरू कसरी सम्हाल्छ भन्ने सिधा उत्तर, IT र खरिद समीक्षाका लागि लेखिएको।' },
      'android': { title: 'Android का लागि Clickt — Google Play मा निजी परीक्षण', desc: 'Android का लागि Clickt Google Play मा निमन्त्रणा-आधारित परीक्षणमा छ। Android स्क्रिनहरू हेर्नुहोस् र पहुँच अनुरोध गर्नुहोस्।' },
      'privacy': { title: 'गोपनीयता कथन | Clickt', desc: 'Clickt ले के सङ्कलन गर्छ, किन, र तपाईंले के गर्न सक्नुहुन्छ।' },
      'terms': { title: 'सेवाका सर्तहरू | Clickt', desc: 'Clickt प्रयोग गर्दा लागू हुने सर्तहरू।' },
      'user-guide': { title: 'प्रयोगकर्ता निर्देशिका — Clickt बाट अधिकतम लाभ लिनुहोस्', desc: 'हरेक Clickt मोड्युलले कसरी काम गर्छ र किन समय बचाउँछ, छिटो सुरु गर्ने मार्ग र समस्या समाधानसहित।' },
      'pitch-deck': { title: 'Clickt — व्यावसायिक पिच डेक', desc: 'Clickt को व्यावसायिक पिच डेक।' },
      'not-found': { title: 'पृष्ठ फेला परेन | Clickt', desc: 'त्यो पृष्ठ सारिएको छ वा अवस्थित छैन।' },
      'solutions-schools': { title: 'विद्यालयका लागि Clickt — विद्यालय जीवन वरिपरिको काम समन्वय गर्नुहोस्', desc: 'तपाईंको विद्यालय-व्यवस्थापन प्रणालीको छेउमा रहेको परीक्षा-हप्ता, कार्यक्रम र विभागीय काम तोक्नुहोस्, फलोअप गर्नुहोस् र रिपोर्ट गर्नुहोस्।' },
      'solutions-healthcare': { title: 'स्वास्थ्य सेवाका लागि Clickt — गैर-क्लिनिकल समन्वय', desc: 'क्लिनिकल र अस्पताल प्रणालीको छेउमा मर्मत, जाँच र शिफ्ट ह्यान्डअफ समन्वय गर्नुहोस्।' },
      'solutions-banks': { title: 'बैंकका लागि Clickt — शाखा तयारी र फलोअप', desc: 'कोर बैंकिङ प्रणाली वरिपरि शाखा-तयारी, फलोअप र व्यवस्थापन अपडेट समन्वय गर्नुहोस्।' },
      'solutions-ngos': { title: 'NGO का लागि Clickt — फिल्ड फलोअप र रिपोर्टिङ', desc: 'दाता र M&E प्रणालीको छेउमा फिल्ड फलोअप, कार्यक्रम गतिविधि र रिपोर्टिङ समन्वय गर्नुहोस्।' },
      'solutions-hotels': { title: 'होटलका लागि Clickt — सेवा रिकभरी र ह्यान्डअफ', desc: 'तपाईंको PMS र बुकिङ प्रणालीको छेउमा सेवा रिकभरी, सुविधा र शिफ्ट ह्यान्डअफ समन्वय गर्नुहोस्।' },
      'solutions-restaurants': { title: 'रेस्टुरेन्टका लागि Clickt — खोल्ने, सेवा र बन्द गर्ने दिनचर्या', desc: 'तपाईंको POS र भण्डार प्रणालीसँगै खोल्ने, सेवा र बन्द गर्ने दिनचर्या समन्वय गर्नुहोस्।' },
      'solutions-construction': { title: 'निर्माण र घरजग्गाका लागि Clickt — साइट फलोअप', desc: 'परियोजना र लेखा प्रणालीसँगै साइट फलोअप, त्रुटि समाधान र खरिद समन्वय गर्नुहोस्।' },
  } },
};
