// Notes: the page copy, the interactive scene, navigation labels, and the places where the
// four-module story ("Teams, Checklist, Builder and Presentation") became five.
// Loaded last, so anything here overrides older copy.
export default {
  en: {
    meta: {
      notes: {
        title: 'Notes — Turn what you write and say into work | Clickt',
        desc: 'Write notes, draft them with AI, record a meeting, then extract the work and send it to your Checklist or your Teams. You review every item before anything is created.',
      },
      home: {
        title: 'Clickt — AI that prepares the work. You make the call.',
        desc: 'Teams, Notes, Checklist, Builder and Presentation in one workspace. ClicktAI drafts every task, chart and deck for your review, and applies nothing without your approval. iPhone, iPad, Mac and Android.',
      },
      clicktai: {
        desc: 'ClicktAI prepares work across Teams, Checklist, Builder and Presentation, and Notes can draft and extract work with the same AI key. You review every proposal before anything changes, and you bring your own AI key.',
      },
    },
    siteShell: { product: { notes: 'Notes' } },
    shell: { menu: { notes: 'Write, record, then turn it into work' } },
    prod: {
      seeNotes: { title: 'Pull the work <em>out</em> of the note.', lead: 'Extract the action items from a meeting note, choose where each one goes, and watch only the ones you pick get created.' },
    },
    scene: {
      notes: {
        noteTitle: 'Clickt rollout kickoff',
        noteKicker: 'Meeting note',
        noteBody: 'Sam will set up the team workspace by Friday. Priya to send the onboarding invites. We should also review the weekly usage numbers before the leadership update.',
        extract: 'Extract work',
        working: 'Reading the note…',
        sent: 'The selected note text is sent to your configured AI provider.',
        head: 'Review the drafts',
        d1: 'Set up the team workspace',
        d2: 'Send the onboarding invites',
        d3: 'Review weekly usage before the update',
        leave: 'Leave open',
        checklist: 'Checklist',
        teams: 'Teams',
        hint: 'Every draft starts as Leave open. Nothing is created until you confirm it.',
        confirm: 'Confirm choices',
        receipt: '{c} to Checklist · {t} to Teams · {l} left open',
        receiptSub: 'Each one is created only after you confirm it.',
        reset: 'Watch again',
      },
    },
    home: {
      hero: {
        title: '<span class="ln">AI that <em>prepares</em> the work.</span> <span class="ln">You make the <em>call.</em></span>',
        lead: 'Teams, Notes, Checklist, Builder and Presentation in one workspace. ClicktAI drafts every task, chart and deck for your review, and applies nothing without your approval.',
        phoneAlt: 'Clickt home screen on iPhone with Teams, Notes, Builder and Presentation',
      },
      ch1: {
        notes: { k: 'Notes', h: 'From a page of notes to a list of work.', b: 'Write a note, draft one with AI or record a meeting, then extract the work and send it to your Checklist or your Teams.', l: 'Explore Notes' },
      },
      chNotes: {
        slate: 'Chapter 03',
        name: 'Notes',
        title: 'From a meeting to a <em>to-do list.</em>',
        lead: 'Write it, draft it with AI, or record the meeting. Then extract the work and decide where each item goes: your Checklist, your Teams, or nowhere yet.',
        cta: 'See how Notes works',
        shotAlt: 'Extract Work in Clickt Notes on Mac, with a destination chosen for each draft',
      },
      devices: {
        ipadAltHome: 'Clickt home screen on iPad with Teams, Notes, Builder and Presentation',
        notesAlt: 'Clickt Notes recording a meeting on iPhone',
      },
      faq: {
        a1: 'Yes. Free includes Teams, Notes, Checklist, Builder, Presentation and Calendar, and you connect your own AI provider key for ClicktAI. Business adds a company workspace, admin controls and Clickt-provided AI for teams.',
        q6: 'What can I do with Notes?',
        a6: 'Write notes in folders, draft one with AI, or record a meeting into a transcript. Then extract the work from the note and send each item to your personal Checklist or to a team you own. You review every draft first, and nothing is created until you confirm it.',
      },
    },
    pricing: {
      hero: { lead: 'Every plan includes Teams, Notes, Builder, Presentation and Checklist on iPhone, iPad and Mac. On Android, Business organisations get their own app; the free app is in private testing.' },
      tiers: { free: { feature1: 'Teams, Notes, Builder, Presentation &amp; Checklist' } },
      faq: { q1: { answer: 'The Free plan includes the full Clickt workflow - Teams, Notes, Builder, Presentation, Checklist, and Calendar - for individuals and small teams. You can use every ClicktAI Copilot, and AI in Notes, by connecting your own AI provider API key in Settings.' } },
    },
    solutions: {
      principles: { twoCopy: 'Teams assigns the work, Notes captures what was said, Checklist keeps recurring work consistent, Builder clarifies data, and Presentation turns progress into a decision-ready story.' },
      notes: {
      kicker: 'Notes',
      title: 'Notes turns every meeting into owned work.',
      lead: 'Whatever your team does, work gets agreed in conversations. Notes captures them and helps you turn them into tasks, checklists and updates.',
      b1: 'Capture once', b1Body: 'Type it, have AI draft it, or record the meeting. No retyping action items afterward.',
      b2: 'Nothing slips', b2Body: 'Extract Work finds the follow-ups buried in a page of notes, so they do not get forgotten.',
      b3: 'The right destination', b3Body: 'Send each item to your own Checklist or to a team you own, as a task, invite or announcement.',
      b4: 'You stay in control', b4Body: 'Every draft is reviewed first. Notes stay on your device, and AI sees only the text you choose to send.',
      rolesTitle: 'How different teams use Notes.',
      rolesLead: 'The same flow, shaped by the work each team does.',
      roleLink: 'See the workflow',
      },
    },
    modulePages: {
      notes: {
        eyebrow: 'Notes',
        heroTitle: 'Write it down. Turn it into work.',
        heroLead: 'Notes is a private place to write, draft with AI or record a meeting. Then Extract Work finds the tasks inside, and you decide which go to your Checklist or your Teams.',
        deviceImgAlt: 'Clickt Notes recording a meeting on iPhone',
        deviceCaptionStrong: 'Record, then review',
        deviceCaptionText: 'A live transcript you can edit before it is saved to Notes.',
        capabilitiesEyebrow: 'What Notes does',
        capabilitiesTitle: 'A calm place to think, with a clear way out.',
        capabilitiesLead: 'Notes starts as plain writing. When a note contains work, you can pull that work out and send it where it belongs, without retyping it.',
        capability1Title: 'Notes in folders',
        capability1Body: 'Write in a simple editor, group notes into folders, pin the ones you need, and search across all of them. Notes work without an AI key.',
        capability2Title: 'Create with AI',
        capability2Body: 'Give ClicktAI a topic, a format and a length. You get an editable draft, can ask for a revision or regenerate it, and the topic becomes the note title. Nothing is saved until you choose Save as Note.',
        capability3Title: 'Extract Work',
        capability3Body: 'ClicktAI reads a note and lists the work hiding inside it. Edit any draft, then send each one to Leave open, Checklist or Teams.',
        capability4Title: 'Send it where it belongs',
        capability4Body: 'Checklist drafts become ordinary checklist items, one at a time. Team drafts go to a team you own as a Task, an Invite or an Announcement. A draft is marked done only after Clickt has actually created it.',
        capability5Title: 'Record a meeting',
        capability5Body: 'Start with a consent screen, record while the screen stays open, and watch a live transcript you can edit. Save it to Notes and the temporary audio is deleted. There is no background recording and no speaker identification.',
        workflowTitle: 'From what was said to what gets done.',
        workflowLead: 'The same four steps work whether you typed the note, asked AI to draft it, or recorded the meeting.',
        step1Title: 'Write or record',
        step1Body: 'Start a note, create one with AI, or record a meeting into a transcript.',
        step2Title: 'Extract the work',
        step2Body: 'Run Extract Work. ClicktAI lists the tasks it finds. You edit, merge or remove them.',
        step3Title: 'Choose a destination',
        step3Body: 'Every draft starts as Leave open. Move it to Checklist or Teams when you are ready.',
        step4Title: 'Confirm, one at a time',
        step4Body: 'Each item opens in the normal Checklist or Teams flow. You confirm it, and the note shows what was sent.',
        scenarioEyebrow: 'The meeting that ended with “I’ll send notes”',
        scenarioTitle: 'The action items nobody wrote down twice.',
        scenarioBeforeLabel: 'Before Notes',
        scenarioBeforeBody: 'The meeting ends and everyone agrees someone will send the notes. A page of text goes into a chat. Someone retypes the action items into a list, someone else forgets one, and the person who owned it finds out on Friday.',
        scenarioAfterLabel: 'With Notes',
        scenarioAfterBody: 'Record the meeting or paste the notes, and run Extract Work. Send your own follow-ups to your Checklist and the team’s to Teams, each one reviewed first. The note keeps a record of what was sent, so nothing is created twice.',
        aiEyebrow: 'Create with AI',
        aiTitle: 'Start from a topic, finish with a note you edited.',
        aiLead: 'Describe what you need, such as an agenda, a study guide or a plan, and choose a format and length. You can also turn on research with sources. Edit the draft, ask for a revision, regenerate, or discard it. Only the text you submit goes to your AI provider, and nothing is saved until you choose Save as Note.',
        screenEyebrow: 'Everything starts from Add',
        screenTitle: 'One menu for every way to begin.',
        screenLead: 'New Note, Create with AI and Record meeting sit together, next to New Folder and Manage Folders. On iPad and Mac, folders and the note list sit beside the editor.',
        screenLinkText: 'See how Teams gives shared work an owner',
        screenImgAlt: 'Clickt Notes on iPad with the Add menu open',
        galleryEyebrow: 'See it work',
        galleryTitle: 'From the first note to the last send.',
        galleryLead: 'Folders and notes on the left, the editor in the middle, and each step of Extract Work and dispatch in its own focused sheet.',
        tab1: 'Write',
        tab1Cap: 'Folders and notes on the left, a focused editor in the middle, and Add to Checklist and Send to Teams ready below.',
        tab1Alt: 'The Clickt Notes workspace on Mac, with a note open in the editor',
        tab2: 'Create with AI',
        tab2Cap: 'Enter a topic, add optional instructions, and choose a format and length. You can research with sources.',
        tab2Alt: 'The Create with AI sheet in Clickt Notes on Mac',
        tab3: 'Extract Work',
        tab3Cap: 'ClicktAI lists the work it found in the note. The note text is sent to your configured AI provider for this step.',
        tab3Alt: 'The Extract Work sheet in Clickt Notes on Mac, listing draft work items',
        tab4: 'Choose a destination',
        tab4Cap: 'Each draft has a Send to menu: Leave open, Checklist or Teams. Leave open is the default.',
        tab4Alt: 'The Send to menu on an extracted work item, showing Leave open, Checklist and Teams',
        tab5: 'Add to Checklist',
        tab5Cap: 'Pick one reviewed draft, edit it if you want, and open it in your Checklist.',
        tab5Alt: 'The Add to Checklist sheet in Clickt Notes on Mac',
        tab6: 'Send to Teams',
        tab6Cap: 'Pick a draft and continue in Teams, where you choose a team you own and send it as a task, an invite or an announcement.',
        tab6Alt: 'The Send to Teams sheet in Clickt Notes on Mac',
        tab7: 'Record meeting',
        tab7Cap: 'Create a private transcript from a live discussion. You start the recording yourself, after you agree to the consent notice.',
        tab7Alt: 'The Record meeting sheet in Clickt Notes on Mac',
        relatedTitle: 'Notes works with the rest of Clickt.',
        relatedLead: 'Notes captures the work. Teams, Checklist, Builder and Presentation help carry it through.',
        relatedTeamsLabel: 'Teams',
        relatedTeamsTitle: 'Send work to a team',
        relatedTeamsBody: 'Send an extracted draft to a team you own as a task, an invite or an announcement.',
        relatedTeamsLink: 'Explore Teams →',
        relatedChecklistLabel: 'Checklist',
        relatedChecklistTitle: 'Add it to your list',
        relatedChecklistBody: 'Turn a note’s action items into personal checklist items, one at a time.',
        relatedChecklistLink: 'Explore Checklist →',
        relatedBuilderLabel: 'Builder',
        relatedBuilderTitle: 'Back it with data',
        relatedBuilderBody: 'When a note raises a question, analyse the numbers behind it.',
        relatedBuilderLink: 'Explore Builder →',
        relatedPresentationLabel: 'Presentation',
        relatedPresentationTitle: 'Share the outcome',
        relatedPresentationBody: 'Turn what a meeting decided into a deck people can review together.',
        relatedPresentationLink: 'Explore Presentation →',
        finalEyebrow: 'Capture less, finish more',
        finalTitle: 'Let the note do the remembering.',
        finalLead: 'Notes is in Clickt on iPhone, iPad and Mac, and also on Android, which is in private testing. It is included in every plan.',
      },
      teams: {
        relatedNotesLabel: 'Notes',
        relatedNotesTitle: 'Work from meetings',
        relatedNotesBody: 'Record or write the meeting, extract the work, and send it to a team you own.',
        relatedNotesLink: 'Explore Notes →',
      },
      checklist: {
        relatedNotesLabel: 'Notes',
        relatedNotesTitle: 'Start from a note',
        relatedNotesBody: 'Extract action items from a note and add them to your list, one at a time.',
        relatedNotesLink: 'Explore Notes →',
        relatedLead: 'Checklist keeps the repeated steps clear. Notes, Teams, Builder and Presentation help carry ownership, evidence and updates further.',
      },
      builder: {
        relatedNotesLabel: 'Notes',
        relatedNotesTitle: 'Capture the context',
        relatedNotesBody: 'Keep the notes and meetings behind an analysis next to the work it leads to.',
        relatedNotesLink: 'Explore Notes →',
        relatedLead: 'Builder prepares the evidence. Notes, Teams, Checklist and Presentation give that evidence a clear operational next step.',
      },
      presentation: {
        relatedNotesLabel: 'Notes',
        relatedNotesTitle: 'Draft the story first',
        relatedNotesBody: 'Collect your thinking in a note, then turn it into a deck.',
        relatedNotesLink: 'Explore Notes →',
      },
    },
    userGuide: {
      toc: { items: { notes: 'Notes' } },
      notes: {
        heading: 'Notes <a class="anchor-copy" href="#notes" aria-label="Copy link" title="Copy section link">🔗</a>',
        subtitle: 'Write it down, then turn it into work',
        intro: 'Notes is where you write, draft with AI, or record a meeting. When a note contains work, Extract Work lists it as drafts, and you choose where each one goes. Nothing is created until you confirm it.',
        item1: 'Tap Add to start a New Note, Create with AI, or Record meeting. Group notes into folders and search across them.',
        item2: 'Create with AI: enter a topic, choose a format and length, then edit the draft, ask for a revision, or regenerate it. The topic becomes the title, and nothing is saved until you choose Save as Note.',
        item3: 'Extract Work: each draft starts as Leave open. Choose Checklist or Teams for the ones you want to send, then save your choices.',
        item4: 'Add to Checklist and Send to Teams open one draft at a time. Teams items go to a team you own as a task, an invite, or an announcement.',
        item5: 'Record meeting: read and accept the consent notice, keep the screen open while you record, edit the live transcript, then save it to Notes. The temporary audio is deleted afterwards. Always tell participants you are recording.',
        item6: 'AI features send only the note text you choose to your connected AI provider.',
      },
    },
    index: { testing: {
      title: 'Try Clickt on Android.',
      body: 'We’re testing with a small group on Google Play. Ask for an invite and we’ll add your Google account.',
      noteBody: 'Tap Request access. We’ll open a pre-filled email to us and the Google Play tester page. Send the email and you’re in the queue.',
      continue: 'Request access',
    } },
    privacy: {
      section1: { body: 'We collect only what is necessary to run Clickt on Apple and Android devices.', itemNotes: '<strong>Notes and meeting transcripts</strong> you create in Notes - these are stored on your device, not on Clickt\'s servers.' },
      notes: {
        heading: 'Notes, microphone and speech recognition',
        body1: 'Notes, folders and meeting transcripts stay on your device, in private storage for your account. We do not upload them to Clickt, and they do not sync between devices. When you delete a note, it is removed from your device.',
        body2: 'If you choose Record meeting, Clickt asks for microphone and speech recognition permission only after you accept a consent notice, and it records only while the recording screen is open. The audio is written to a temporary private file and deleted when the transcript is saved, or when you cancel. Clickt does not upload raw audio to its servers. Your device\'s speech recognition service, provided by Apple or Google, may process your speech under its own terms.',
        body3: 'Clickt does not identify speakers, record in the background, or capture phone calls or system audio. You are responsible for telling the people you record and for following the recording laws that apply to you.',
      },
      section4: { bodyNotes: 'In Notes, Create with AI and Extract Work send only the note text, topic or instructions you choose to submit, and only when you ask. The results are drafts. Nothing is saved, and no Checklist item or Teams record is created, until you review and confirm it.' },
    },
    terms: {
      section4: {
        body1: 'You own the content you create in Clickt - your tasks, notes, checklists, Builder datasets, and Presentation decks ("your content"). You grant Clickt a limited license to host, process, transmit, and back up your content solely to provide and support the service, including sending relevant content to an AI provider when you ask a ClicktAI Copilot or AI in Notes for help, as described in our <a href="privacy.html">Privacy Statement</a>.',
        bodyRecording: 'If you use Record meeting in Notes, you are solely responsible for telling everyone being recorded, for getting any consent that applicable law requires, and for complying with the recording and privacy laws where you and the participants are located. Do not record anyone who has not been told or who has objected. Clickt provides the recording and transcription tools but is not responsible for how you use them.',
      },
      section5: { bodyNotes: 'AI in Notes - Create with AI, Extract Work and meeting summaries - works the same way. It produces drafts for you to review, and these terms apply to it in the same way.' },
      section6: { bodyNotes: 'The same applies to AI in Notes. Meeting transcription also uses the speech recognition service built into your device, which is provided by Apple or Google and governed by their terms. Clickt is not responsible for that service.' },
    },
    security: {
      dataInfra: {
        notes: { q: 'Where are Notes stored?', a: 'On the user\'s device, in private storage for their account. Notes, folders and meeting transcripts are not uploaded to Clickt\'s cloud, so they do not sync between devices. Something leaves a note only when the user sends it on: a confirmed Checklist item, a Teams task, invite or announcement, or text submitted to an AI provider.' },
        meetings: { q: 'What happens to meeting recordings?', a: 'Recording runs only while the recording screen is open, after the user accepts a consent notice. Audio goes to a temporary private file and is deleted when the transcript is saved or the recording is cancelled. Clickt does not upload raw audio to its servers. The device\'s speech recognition service (Apple or Google) may process the speech. Clickt does not identify speakers, record in the background, or capture calls.' },
      },
      ai: { providers: { a: 'Only the content relevant to the specific request from the module you\'re working in - never your whole workspace. In Notes, only the text the user chooses to submit for Create with AI or Extract Work. On Free, you connect your own provider key. On Business, your admin assigns a Clickt-approved provider.' } },
    },
    industryPages: {
      common: { notesLabel: 'Notes in practice', notesTitle: 'Turn what is said in meetings into work that is owned.', notesLead: 'Notes works the same way for every team. Only the meetings change.', notesB1: 'Capture without retyping', notesB1Body: 'Write, dictate or record the meeting. No copying action items into a list afterward.', notesB2: 'Send work where it belongs', notesB2Body: 'Each follow-up goes to your own Checklist or to a team you own.', notesB3: 'Review before anything is created', notesB3Body: 'Every draft is checked by a person first. Notes stay on your device.' },
      schools: { notesRole: 'Principals, department heads and administrators', notes: 'Record the staff or exam-planning meeting, extract the follow-ups, and send each one to the right person or to your own Checklist.', notesScenario: 'After a staff meeting, a department head records or types the notes. Extract Work lists the actions, such as booking the hall, printing papers and confirming invigilators, and each one goes to the person who owns it in Teams or onto the head’s own Checklist.' },
      healthcare: { notesRole: 'Operations, facilities and nursing administrators', notes: 'Capture non-clinical shift handoffs and maintenance meetings, and turn the follow-ups into owned tasks.', notesScenario: 'A facilities manager notes a handoff meeting about equipment checks and room readiness. Extract Work turns the follow-ups into tasks for the next shift. Use Notes for non-clinical coordination only, never for patient information.' },
      banks: { notesRole: 'Branch managers and operations teams', notes: 'Turn branch-readiness and management meetings into owned follow-ups, without retyping.', notesScenario: 'A branch manager writes up the weekly readiness meeting. Extract Work lists the actions, such as staffing cover, signage and training refreshers, and each is assigned in Teams or kept on the manager’s Checklist. Keep Notes to internal coordination, not customer account details.' },
      ngos: { notesRole: 'Programme officers and field coordinators', notes: 'Capture field visits and partner meetings, then turn the agreed actions into follow-ups for the team.', notesScenario: 'After a field visit, a programme officer records the debrief. Extract Work lists the follow-ups, such as sending the attendance report and confirming the next distribution, and sends each one to the right person or to their own Checklist.' },
      hotels: { notesRole: 'General managers and department heads', notes: 'Write up daily briefings and service-recovery meetings, and send the follow-ups to the right shift.', notesScenario: 'A duty manager records the morning briefing. Extract Work picks out the actions, such as fixing a room fault, restocking the lounge and calling back a guest, and assigns them to the right department in Teams.' },
      restaurants: { notesRole: 'Owners and shift managers', notes: 'Capture pre-shift briefings and closing notes, and turn what was said into assigned tasks.', notesScenario: 'A shift manager dictates the closing notes. Extract Work lists the follow-ups, such as reordering stock, fixing the fryer and updating the specials board, and each goes to the person responsible.' },
      construction: { notesRole: 'Site engineers and project managers', notes: 'Record site meetings and snag walks, and turn each agreed action into an owned task.', notesScenario: 'After a site meeting, a project manager records the discussion. Extract Work lists the actions, such as confirming a delivery, rechecking a pour and closing a snag, and sends each to the right foreman or supervisor in Teams.' },
    },
    clicktai: { benefits: { oneBody: 'One request can connect work that would otherwise be rebuilt separately in Teams, Checklist, Builder, and Presentation. Notes uses the same AI key to draft notes and extract work.' } },
  },
  ne: {
    meta: {
      notes: {
        title: 'Notes — तपाईंले लेखेको र भनेको कुरालाई काममा बदल्नुहोस् | Clickt',
        desc: 'नोट लेख्नुहोस्, AI ले ड्राफ्ट गर्नुहोस्, बैठक रेकर्ड गर्नुहोस्, अनि काम निकालेर आफ्नो Checklist वा Teams मा पठाउनुहोस्। केही बन्नुअघि हरेक वस्तु तपाईंले समीक्षा गर्नुहुन्छ।',
      },
      home: {
        title: 'Clickt — काम तयार गर्ने AI। निर्णय तपाईंको।',
        desc: 'Teams, Notes, Checklist, Builder र Presentation एउटै कार्यक्षेत्रमा। ClicktAI ले हरेक कार्य, चार्ट र डेक तपाईंको समीक्षाका लागि ड्राफ्ट गर्छ, र तपाईंको स्वीकृतिबिना केही लागू गर्दैन। iPhone, iPad, Mac र Android।',
      },
      clicktai: {
        desc: 'ClicktAI ले Teams, Checklist, Builder र Presentation भरि काम तयार गर्छ, र Notes ले उही AI की प्रयोग गरेर नोट ड्राफ्ट गर्छ र काम निकाल्छ। केही बदलिनुअघि हरेक प्रस्ताव तपाईंले समीक्षा गर्नुहुन्छ, र आफ्नै AI की ल्याउनुहुन्छ।',
      },
    },
    siteShell: { product: { notes: 'नोट्स' } },
    shell: { menu: { notes: 'लेख्नुहोस्, रेकर्ड गर्नुहोस्, काममा बदल्नुहोस्' } },
    prod: {
      seeNotes: { title: 'नोटबाट काम <em>निकाल्नुहोस्।</em>', lead: 'बैठकको नोटबाट कार्य बुँदा निकाल्नुहोस्, हरेक बुँदा कहाँ जाने रोज्नुहोस्, र तपाईंले रोजेका मात्र बनेको हेर्नुहोस्।' },
    },
    scene: {
      notes: {
        noteTitle: 'Clickt रोलआउट सुरुवाती बैठक',
        noteKicker: 'बैठकको नोट',
        noteBody: 'राम शुक्रबारसम्म टोलीको कार्यक्षेत्र सेटअप गर्छन्। प्रिया अनबोर्डिङ निमन्त्रणा पठाउँछिन्। नेतृत्वको अपडेटअघि साप्ताहिक प्रयोगको तथ्यांक पनि हेर्नुपर्छ।',
        extract: 'काम निकाल्नुहोस्',
        working: 'नोट पढ्दै…',
        sent: 'चयन गरिएको नोटको पाठ तपाईंले जोडेको AI प्रदायकलाई पठाइन्छ।',
        head: 'ड्राफ्टहरू समीक्षा गर्नुहोस्',
        d1: 'टोलीको कार्यक्षेत्र सेटअप गर्ने',
        d2: 'अनबोर्डिङ निमन्त्रणा पठाउने',
        d3: 'अपडेटअघि साप्ताहिक प्रयोग हेर्ने',
        leave: 'खुला राख्नुहोस्',
        checklist: 'Checklist',
        teams: 'Teams',
        hint: 'हरेक ड्राफ्ट “खुला राख्नुहोस्” बाट सुरु हुन्छ। तपाईंले पुष्टि नगरेसम्म केही बन्दैन।',
        confirm: 'छनोट पुष्टि गर्नुहोस्',
        receipt: '{c} Checklist मा · {t} Teams मा · {l} खुला',
        receiptSub: 'हरेक वस्तु तपाईंले पुष्टि गरेपछि मात्र बनाइन्छ।',
        reset: 'फेरि हेर्नुहोस्',
      },
    },
    home: {
      hero: {
        title: '<span class="ln">काम तयार गर्ने <em>AI।</em></span> <span class="ln">निर्णय <em>तपाईंको।</em></span>',
        lead: 'Teams, Notes, Checklist, Builder र Presentation एउटै कार्यक्षेत्रमा। ClicktAI ले हरेक कार्य, चार्ट र डेक तपाईंको समीक्षाका लागि ड्राफ्ट गर्छ, र तपाईंको स्वीकृतिबिना केही लागू गर्दैन।',
        phoneAlt: 'iPhone मा Clickt को गृह स्क्रिन, Teams, Notes, Builder र Presentation सहित',
      },
      ch1: {
        notes: { k: 'Notes', h: 'नोटको पानाबाट कामको सूचीसम्म।', b: 'नोट लेख्नुहोस्, AI ले ड्राफ्ट गर्नुहोस् वा बैठक रेकर्ड गर्नुहोस्, अनि काम निकालेर आफ्नो Checklist वा Teams मा पठाउनुहोस्।', l: 'Notes हेर्नुहोस्' },
      },
      chNotes: {
        slate: 'अध्याय ०३',
        name: 'नोट्स',
        title: 'बैठकबाट <em>कामको सूचीसम्म।</em>',
        lead: 'लेख्नुहोस्, AI ले ड्राफ्ट गर्नुहोस्, वा बैठक रेकर्ड गर्नुहोस्। अनि काम निकाल्नुहोस् र हरेक वस्तु कहाँ जाने निर्णय गर्नुहोस्: तपाईंको Checklist, तपाईंको Teams, वा अहिलेलाई कतै होइन।',
        cta: 'Notes कसरी काम गर्छ हेर्नुहोस्',
        shotAlt: 'Mac मा Clickt Notes को “काम निकाल्नुहोस्”, हरेक ड्राफ्टको गन्तव्य रोजिएको',
      },
      devices: {
        ipadAltHome: 'iPad मा Clickt को गृह स्क्रिन, Teams, Notes, Builder र Presentation सहित',
        notesAlt: 'iPhone मा बैठक रेकर्ड गर्दै Clickt Notes',
      },
      faq: {
        a1: 'हो। निःशुल्क योजनामा Teams, Notes, Checklist, Builder, Presentation र पात्रो समावेश छन्, र ClicktAI का लागि तपाईंले आफ्नै AI प्रदायकको की जोड्नुहुन्छ। बिजनेसले कम्पनी कार्यक्षेत्र, एडमिन नियन्त्रण र टोलीका लागि Clickt-प्रदत्त AI थप्छ।',
        q6: 'Notes बाट के गर्न सकिन्छ?',
        a6: 'फोल्डरमा नोट लेख्नुहोस्, AI ले एउटा ड्राफ्ट गर्नुहोस्, वा बैठक रेकर्ड गरेर ट्रान्सक्रिप्ट बनाउनुहोस्। त्यसपछि नोटबाट काम निकालेर हरेक वस्तु आफ्नो व्यक्तिगत Checklist वा तपाईंले चलाउने टोलीमा पठाउनुहोस्। हरेक ड्राफ्ट पहिले तपाईंले समीक्षा गर्नुहुन्छ, र पुष्टि नगरेसम्म केही बन्दैन।',
      },
    },
    pricing: {
      hero: { lead: 'हरेक योजनामा iPhone, iPad र Mac मा Teams, Notes, Builder, Presentation र Checklist समावेश छ। Android मा Business संस्थाहरूले आफ्नै एप पाउँछन्; नि:शुल्क एप निजी परीक्षणमा छ।' },
      tiers: { free: { feature1: 'Teams, Notes, Builder, Presentation &amp; Checklist' } },
      faq: { q1: { answer: 'निःशुल्क योजनामा पूरा Clickt वर्कफ्लो - Teams, Notes, Builder, Presentation, Checklist, र Calendar - व्यक्ति र साना टोलीका लागि समावेश छ। सेटिङ्समा आफ्नै AI प्रदायकको API की जोडेर तपाईंले हरेक ClicktAI कोपाइलट र Notes भित्रको AI प्रयोग गर्न सक्नुहुन्छ।' } },
    },
    solutions: {
      principles: { twoCopy: 'Teams ले काम बाँड्छ, Notes ले भनिएको कुरा समात्छ, Checklist ले दोहोरिने कामलाई एकरूप राख्छ, Builder ले डेटा स्पष्ट पार्छ, र Presentation ले प्रगतिलाई निर्णय गर्न मिल्ने कथामा बदल्छ।' },
      notes: {
      kicker: 'Notes',
      title: 'Notes ले हरेक बैठकलाई जिम्मेवार कामको रूप दिन्छ।',
      lead: 'तपाईंको टोलीले जेसुकै गरे पनि, काम कुराकानीमै तय हुन्छ। Notes ले तिनलाई समात्छ र कार्य, चेकलिस्ट र अपडेटमा बदल्न सघाउँछ।',
      b1: 'एक पटक समात्नुहोस्', b1Body: 'टाइप गर्नुहोस्, AI ले ड्राफ्ट गर्नुहोस्, वा बैठक रेकर्ड गर्नुहोस्। पछि कार्य बुँदा फेरि टाइप गर्नु पर्दैन।',
      b2: 'केही छुट्दैन', b2Body: '“काम निकाल्नुहोस्” ले नोटको पानाभित्र लुकेका फलो-अप भेट्छ, त्यसैले तिनलाई बिर्सिँदैन।',
      b3: 'उपयुक्त गन्तव्य', b3Body: 'हरेक वस्तु आफ्नो Checklist वा तपाईंले चलाउने टोलीमा कार्य, निमन्त्रणा वा घोषणाको रूपमा पठाउनुहोस्।',
      b4: 'नियन्त्रण तपाईंमै', b4Body: 'हरेक ड्राफ्ट पहिले समीक्षा हुन्छ। नोट तपाईंको उपकरणमै रहन्छन्, र AI ले तपाईंले पठाउन रोजेको पाठ मात्र देख्छ।',
      rolesTitle: 'फरक-फरक टोलीले Notes कसरी प्रयोग गर्छन्।',
      rolesLead: 'उही प्रवाह, हरेक टोलीको कामअनुसार ढालिएको।',
      roleLink: 'कार्यप्रवाह हेर्नुहोस्',
      },
    },
    modulePages: {
      notes: {
        eyebrow: 'Notes',
        heroTitle: 'लेख्नुहोस्। काममा बदल्नुहोस्।',
        heroLead: 'Notes लेख्ने, AI ले ड्राफ्ट गर्ने वा बैठक रेकर्ड गर्ने निजी ठाउँ हो। त्यसपछि “काम निकाल्नुहोस्” ले भित्रका कार्यहरू भेट्छ, र कुन तपाईंको Checklist वा Teams मा जाने भन्ने तपाईं तय गर्नुहुन्छ।',
        deviceImgAlt: 'iPhone मा बैठक रेकर्ड गर्दै Clickt Notes',
        deviceCaptionStrong: 'रेकर्ड गर्नुहोस्, अनि समीक्षा',
        deviceCaptionText: 'Notes मा सुरक्षित गर्नुअघि सम्पादन गर्न मिल्ने प्रत्यक्ष ट्रान्सक्रिप्ट।',
        capabilitiesEyebrow: 'Notes ले के गर्छ',
        capabilitiesTitle: 'सोच्नका लागि शान्त ठाउँ, र बाहिर निस्कने स्पष्ट बाटो।',
        capabilitiesLead: 'Notes साधारण लेखनबाट सुरु हुन्छ। नोटमा काम भए, त्यो निकालेर फेरि टाइप नगरी उपयुक्त ठाउँमा पठाउन सकिन्छ।',
        capability1Title: 'फोल्डरमा नोट',
        capability1Body: 'सरल सम्पादकमा लेख्नुहोस्, नोटलाई फोल्डरमा समूहबद्ध गर्नुहोस्, चाहिनेलाई पिन गर्नुहोस्, र सबैमा खोज्नुहोस्। AI की बिना पनि Notes चल्छ।',
        capability2Title: 'AI ले बनाउनुहोस्',
        capability2Body: 'ClicktAI लाई विषय, ढाँचा र लम्बाइ दिनुहोस्। सम्पादन गर्न मिल्ने ड्राफ्ट आउँछ, संशोधन माग्न वा पुनः बनाउन सकिन्छ, र विषय नै नोटको शीर्षक बन्छ। “नोटको रूपमा सुरक्षित गर्नुहोस्” नछानेसम्म केही सुरक्षित हुँदैन।',
        capability3Title: 'काम निकाल्नुहोस्',
        capability3Body: 'ClicktAI ले नोट पढेर भित्र लुकेको काम सूचीबद्ध गर्छ। जुनसुकै ड्राफ्ट सम्पादन गरेर हरेकलाई खुला राख्नुहोस्, Checklist वा Teams मा पठाउनुहोस्।',
        capability4Title: 'उपयुक्त ठाउँमा पठाउनुहोस्',
        capability4Body: 'Checklist ड्राफ्ट एक-एक गरेर सामान्य चेकलिस्ट वस्तु बन्छन्। टोलीका ड्राफ्ट तपाईंले चलाउने टोलीमा कार्य, निमन्त्रणा वा घोषणाको रूपमा जान्छन्। Clickt ले साँच्चै बनाएपछि मात्र ड्राफ्ट सम्पन्न चिनो लाग्छ।',
        capability5Title: 'बैठक रेकर्ड गर्नुहोस्',
        capability5Body: 'सहमतिको स्क्रिनबाट सुरु गर्नुहोस्, स्क्रिन खुला रहँदा रेकर्ड गर्नुहोस्, र सम्पादन गर्न मिल्ने प्रत्यक्ष ट्रान्सक्रिप्ट हेर्नुहोस्। Notes मा सुरक्षित गरेपछि अस्थायी अडियो मेटिन्छ। पृष्ठभूमि रेकर्डिङ र बोल्ने व्यक्ति पहिचान छैन।',
        workflowTitle: 'के भनियो भन्नेदेखि के गरियो भन्नेसम्म।',
        workflowLead: 'नोट टाइप गर्नुभए पनि, AI ले ड्राफ्ट गरे पनि, वा बैठक रेकर्ड गर्नुभए पनि उही चार चरण लाग्छ।',
        step1Title: 'लेख्नुहोस् वा रेकर्ड गर्नुहोस्',
        step1Body: 'नोट सुरु गर्नुहोस्, AI ले बनाउनुहोस्, वा बैठक रेकर्ड गरेर ट्रान्सक्रिप्ट बनाउनुहोस्।',
        step2Title: 'काम निकाल्नुहोस्',
        step2Body: '“काम निकाल्नुहोस्” चलाउनुहोस्। ClicktAI ले भेटेका कार्य सूचीबद्ध गर्छ। तपाईं सम्पादन, मिलाउन वा हटाउन सक्नुहुन्छ।',
        step3Title: 'गन्तव्य रोज्नुहोस्',
        step3Body: 'हरेक ड्राफ्ट “खुला राख्नुहोस्” बाट सुरु हुन्छ। तयार हुँदा Checklist वा Teams मा सार्नुहोस्।',
        step4Title: 'एक-एक गरेर पुष्टि गर्नुहोस्',
        step4Body: 'हरेक वस्तु सामान्य Checklist वा Teams प्रवाहमा खुल्छ। तपाईंले पुष्टि गर्नुहुन्छ, र नोटले के पठाइयो देखाउँछ।',
        scenarioEyebrow: '“म नोट पठाउँछु” भनेर टुंगिएको बैठक',
        scenarioTitle: 'दुई पटक कसैले नलेखेका कार्य बुँदा।',
        scenarioBeforeLabel: 'Notes अघि',
        scenarioBeforeBody: 'बैठक सकिन्छ र कसैले नोट पठाउने कुरामा सबै सहमत हुन्छन्। एक पाना पाठ च्याटमा जान्छ। कसैले कार्य बुँदा सूचीमा फेरि टाइप गर्छ, अर्काले एउटा छुटाउँछ, र जिम्मेवार व्यक्तिलाई शुक्रबार मात्र थाहा हुन्छ।',
        scenarioAfterLabel: 'Notes सँग',
        scenarioAfterBody: 'बैठक रेकर्ड गर्नुहोस् वा नोट टाँस्नुहोस्, अनि “काम निकाल्नुहोस्” चलाउनुहोस्। आफ्ना फलो-अप Checklist मा र टोलीका Teams मा पठाउनुहोस्, हरेक पहिले समीक्षा गरेर। नोटले के पठाइयो भन्ने अभिलेख राख्छ, त्यसैले केही दुई पटक बन्दैन।',
        aiEyebrow: 'AI ले बनाउनुहोस्',
        aiTitle: 'विषयबाट सुरु गर्नुहोस्, आफैँ सम्पादन गरेको नोटमा टुंग्याउनुहोस्।',
        aiLead: 'एजेन्डा, अध्ययन गाइड वा योजना जस्तो चाहिएको कुरा वर्णन गरेर ढाँचा र लम्बाइ रोज्नुहोस्। स्रोतसहित अनुसन्धान पनि खोल्न सकिन्छ। ड्राफ्ट सम्पादन गर्नुहोस्, संशोधन माग्नुहोस्, पुनः बनाउनुहोस् वा खारेज गर्नुहोस्। तपाईंले पठाएको पाठ मात्र AI प्रदायकमा जान्छ, र “नोटको रूपमा सुरक्षित गर्नुहोस्” नछानेसम्म केही सुरक्षित हुँदैन।',
        screenEyebrow: 'सबै कुरा “Add” बाट सुरु',
        screenTitle: 'सुरु गर्ने हरेक तरिकाको एउटै मेनु।',
        screenLead: 'नयाँ नोट, AI ले बनाउनुहोस् र बैठक रेकर्ड एकै ठाउँमा छन्, नयाँ फोल्डर र फोल्डर व्यवस्थापनको छेउमा। iPad र Mac मा फोल्डर र नोट सूची सम्पादकको छेउमा बस्छन्।',
        screenLinkText: 'Teams ले साझा कामलाई कसरी जिम्मेवार दिन्छ हेर्नुहोस्',
        screenImgAlt: 'iPad मा Clickt Notes, Add मेनु खुला',
        galleryEyebrow: 'काम गरेको हेर्नुहोस्',
        galleryTitle: 'पहिलो नोटदेखि अन्तिम पठाइसम्म।',
        galleryLead: 'बायाँ फोल्डर र नोट, बीचमा सम्पादक, र काम निकाल्ने र पठाउने हरेक चरण आफ्नै केन्द्रित सिटमा।',
        tab1: 'लेख्नुहोस्',
        tab1Cap: 'बायाँ फोल्डर र नोट, बीचमा केन्द्रित सम्पादक, र तल Checklist मा थप्ने र Teams मा पठाउने बटन तयार।',
        tab1Alt: 'Mac मा Clickt Notes कार्यक्षेत्र, सम्पादकमा नोट खुला',
        tab2: 'AI ले बनाउनुहोस्',
        tab2Cap: 'विषय लेख्नुहोस्, चाहे निर्देशन थप्नुहोस्, र ढाँचा र लम्बाइ रोज्नुहोस्। स्रोतसहित अनुसन्धान गर्न सकिन्छ।',
        tab2Alt: 'Mac मा Clickt Notes को “AI ले बनाउनुहोस्” सिट',
        tab3: 'काम निकाल्नुहोस्',
        tab3Cap: 'ClicktAI ले नोटमा भेटेको काम सूचीबद्ध गर्छ। यो चरणमा नोटको पाठ तपाईंले जोडेको AI प्रदायकलाई पठाइन्छ।',
        tab3Alt: 'Mac मा Clickt Notes को “काम निकाल्नुहोस्” सिट, ड्राफ्ट कार्यहरू सहित',
        tab4: 'गन्तव्य रोज्नुहोस्',
        tab4Cap: 'हरेक ड्राफ्टमा “पठाउने ठाउँ” मेनु छ: खुला राख्नुहोस्, Checklist वा Teams। खुला राख्नु पूर्वनिर्धारित हो।',
        tab4Alt: 'निकालिएको कार्यको “पठाउने ठाउँ” मेनु, खुला राख्नुहोस्, Checklist र Teams सहित',
        tab5: 'Checklist मा थप्नुहोस्',
        tab5Cap: 'समीक्षा गरिएको एउटा ड्राफ्ट रोज्नुहोस्, चाहे सम्पादन गर्नुहोस्, र आफ्नो Checklist मा खोल्नुहोस्।',
        tab5Alt: 'Mac मा Clickt Notes को “Checklist मा थप्नुहोस्” सिट',
        tab6: 'Teams मा पठाउनुहोस्',
        tab6Cap: 'ड्राफ्ट रोजेर Teams मा जारी राख्नुहोस्, जहाँ तपाईंले चलाउने टोली रोजेर कार्य, निमन्त्रणा वा घोषणाको रूपमा पठाउनुहुन्छ।',
        tab6Alt: 'Mac मा Clickt Notes को “Teams मा पठाउनुहोस्” सिट',
        tab7: 'बैठक रेकर्ड',
        tab7Cap: 'प्रत्यक्ष छलफलबाट निजी ट्रान्सक्रिप्ट बनाउनुहोस्। सहमति सूचना स्वीकार गरेपछि रेकर्डिङ तपाईं आफैँ सुरु गर्नुहुन्छ।',
        tab7Alt: 'Mac मा Clickt Notes को “बैठक रेकर्ड” सिट',
        relatedTitle: 'Notes Clickt को बाँकी भागसँग काम गर्छ।',
        relatedLead: 'Notes ले काम समात्छ। Teams, Checklist, Builder र Presentation ले त्यसलाई पूरा गर्न सघाउँछन्।',
        relatedTeamsLabel: 'Teams',
        relatedTeamsTitle: 'टोलीमा काम पठाउनुहोस्',
        relatedTeamsBody: 'निकालिएको ड्राफ्ट तपाईंले चलाउने टोलीमा कार्य, निमन्त्रणा वा घोषणाको रूपमा पठाउनुहोस्।',
        relatedTeamsLink: 'Teams हेर्नुहोस् →',
        relatedChecklistLabel: 'Checklist',
        relatedChecklistTitle: 'आफ्नो सूचीमा थप्नुहोस्',
        relatedChecklistBody: 'नोटका कार्य बुँदालाई एक-एक गरेर व्यक्तिगत चेकलिस्ट वस्तु बनाउनुहोस्।',
        relatedChecklistLink: 'Checklist हेर्नुहोस् →',
        relatedBuilderLabel: 'Builder',
        relatedBuilderTitle: 'डेटाले पुष्टि गर्नुहोस्',
        relatedBuilderBody: 'नोटले प्रश्न उठाउँदा त्यसको पछाडिका अंकको विश्लेषण गर्नुहोस्।',
        relatedBuilderLink: 'Builder हेर्नुहोस् →',
        relatedPresentationLabel: 'Presentation',
        relatedPresentationTitle: 'नतिजा साझा गर्नुहोस्',
        relatedPresentationBody: 'बैठकले निर्णय गरेको कुरालाई सबैले मिलेर हेर्न मिल्ने डेकमा बदल्नुहोस्।',
        relatedPresentationLink: 'Presentation हेर्नुहोस् →',
        finalEyebrow: 'कम टिप्नुहोस्, धेरै सक्नुहोस्',
        finalTitle: 'सम्झने काम नोटलाई दिनुहोस्।',
        finalLead: 'Notes Clickt मा iPhone, iPad र Mac मा उपलब्ध छ, र Android मा पनि छ, जुन निजी परीक्षणमा छ। यो हरेक योजनामा समावेश छ।',
      },
      teams: {
        relatedNotesLabel: 'Notes',
        relatedNotesTitle: 'बैठकबाट काम',
        relatedNotesBody: 'बैठक रेकर्ड गर्नुहोस् वा लेख्नुहोस्, काम निकाल्नुहोस्, र तपाईंले चलाउने टोलीमा पठाउनुहोस्।',
        relatedNotesLink: 'Notes हेर्नुहोस् →',
      },
      checklist: {
        relatedNotesLabel: 'Notes',
        relatedNotesTitle: 'नोटबाट सुरु गर्नुहोस्',
        relatedNotesBody: 'नोटबाट कार्य बुँदा निकालेर एक-एक गरी आफ्नो सूचीमा थप्नुहोस्।',
        relatedNotesLink: 'Notes हेर्नुहोस् →',
        relatedLead: 'Checklist ले दोहोरिने चरण स्पष्ट राख्छ। Notes, Teams, Builder र Presentation ले जिम्मेवारी, प्रमाण र अपडेटलाई अझ अगाडि लैजान सघाउँछन्।',
      },
      builder: {
        relatedNotesLabel: 'Notes',
        relatedNotesTitle: 'सन्दर्भ समात्नुहोस्',
        relatedNotesBody: 'विश्लेषणका पछाडिका नोट र बैठक त्यसले निम्त्याउने कामको छेउमै राख्नुहोस्।',
        relatedNotesLink: 'Notes हेर्नुहोस् →',
        relatedLead: 'Builder ले प्रमाण तयार गर्छ। Notes, Teams, Checklist र Presentation ले त्यो प्रमाणलाई स्पष्ट अर्को कदम दिन्छन्।',
      },
      presentation: {
        relatedNotesLabel: 'Notes',
        relatedNotesTitle: 'पहिले कथा ड्राफ्ट गर्नुहोस्',
        relatedNotesBody: 'आफ्नो सोच नोटमा जम्मा गर्नुहोस्, अनि त्यसलाई डेकमा बदल्नुहोस्।',
        relatedNotesLink: 'Notes हेर्नुहोस् →',
      },
    },
    userGuide: {
      toc: { items: { notes: 'नोट्स' } },
      notes: {
        heading: 'Notes <a class="anchor-copy" href="#notes" aria-label="Copy link" title="Copy section link">🔗</a>',
        subtitle: 'लेख्नुहोस्, अनि काममा बदल्नुहोस्',
        intro: 'Notes मा तपाईं लेख्नुहुन्छ, AI ले ड्राफ्ट गर्नुहुन्छ वा बैठक रेकर्ड गर्नुहुन्छ। नोटमा काम भए “काम निकाल्नुहोस्” ले त्यसलाई ड्राफ्टको रूपमा सूचीबद्ध गर्छ, र हरेक कहाँ जाने भन्ने तपाईं रोज्नुहुन्छ। तपाईंले पुष्टि नगरेसम्म केही बन्दैन।',
        item1: 'Add थिचेर नयाँ नोट, AI ले बनाउनुहोस् वा बैठक रेकर्ड सुरु गर्नुहोस्। नोटलाई फोल्डरमा समूहबद्ध गर्नुहोस् र खोज्नुहोस्।',
        item2: 'AI ले बनाउनुहोस्: विषय लेख्नुहोस्, ढाँचा र लम्बाइ रोज्नुहोस्, अनि ड्राफ्ट सम्पादन गर्नुहोस्, संशोधन माग्नुहोस् वा पुनः बनाउनुहोस्। विषय नै शीर्षक बन्छ, र “नोटको रूपमा सुरक्षित गर्नुहोस्” नछानेसम्म केही सुरक्षित हुँदैन।',
        item3: 'काम निकाल्नुहोस्: हरेक ड्राफ्ट “खुला राख्नुहोस्” बाट सुरु हुन्छ। पठाउन चाहेकाका लागि Checklist वा Teams रोज्नुहोस्, अनि छनोट सुरक्षित गर्नुहोस्।',
        item4: 'Checklist मा थप्नुहोस् र Teams मा पठाउनुहोस् एक पटकमा एउटा ड्राफ्ट खोल्छन्। Teams का वस्तु तपाईंले चलाउने टोलीमा कार्य, निमन्त्रणा वा घोषणाको रूपमा जान्छन्।',
        item5: 'बैठक रेकर्ड: सहमति सूचना पढेर स्वीकार गर्नुहोस्, रेकर्ड गर्दा स्क्रिन खुला राख्नुहोस्, प्रत्यक्ष ट्रान्सक्रिप्ट सम्पादन गरेर Notes मा सुरक्षित गर्नुहोस्। त्यसपछि अस्थायी अडियो मेटिन्छ। रेकर्ड गर्दै गर्दा सहभागीहरूलाई जानकारी दिनुहोस्।',
        item6: 'AI सुविधाले तपाईंले रोजेको नोटको पाठ मात्र तपाईंले जोडेको AI प्रदायकलाई पठाउँछन्।',
      },
    },
    index: { testing: {
      title: 'Android मा Clickt प्रयोग गरेर हेर्नुहोस्।',
      body: 'हामी Google Play मा सानो समूहसँग परीक्षण गर्दैछौं। निमन्त्रणा माग्नुहोस्, हामी तपाईंको Google खाता थप्नेछौं।',
      noteBody: '“पहुँच अनुरोध गर्नुहोस्” थिच्नुहोस्। हामीले हामीलाई पठाउने तयार इमेल र Google Play परीक्षक पृष्ठ खोल्छौं। इमेल पठाउनुहोस्, तपाईं प्रतीक्षा सूचीमा पर्नुहुन्छ।',
      continue: 'पहुँच अनुरोध गर्नुहोस्',
    } },
    privacy: {
      section1: { body: 'हामीले Apple र Android उपकरणमा Clickt चलाउन आवश्यक कुरा मात्र सङ्कलन गर्छौं।', itemNotes: '<strong>नोट र बैठकको ट्रान्सक्रिप्ट</strong> जुन तपाईंले Notes मा सिर्जना गर्नुहुन्छ - यी तपाईंको उपकरणमा राखिन्छन्, Clickt का सर्भरमा होइन।' },
      notes: {
        heading: 'नोट, माइक्रोफोन र स्पिच रिकग्निसन',
        body1: 'नोट, फोल्डर र बैठकका ट्रान्सक्रिप्ट तपाईंको खाताको निजी भण्डारणमा तपाईंको उपकरणमै रहन्छन्। हामी तिनलाई Clickt मा अपलोड गर्दैनौं, र तिनीहरू उपकरणहरूबीच सिंक हुँदैनन्। तपाईंले नोट मेटाउँदा त्यो तपाईंको उपकरणबाट हटाइन्छ।',
        body2: 'तपाईंले “बैठक रेकर्ड” रोज्नुभयो भने सहमति सूचना स्वीकार गरेपछि मात्र Clickt ले माइक्रोफोन र स्पिच रिकग्निसनको अनुमति मागेर, रेकर्डिङ स्क्रिन खुला रहँदा मात्र रेकर्ड गर्छ। अडियो अस्थायी निजी फाइलमा लेखिन्छ र ट्रान्सक्रिप्ट सुरक्षित भएपछि, वा तपाईंले रद्द गरेपछि, मेटिन्छ। Clickt ले कच्चा अडियो आफ्ना सर्भरमा अपलोड गर्दैन। तपाईंको उपकरणको स्पिच रिकग्निसन सेवा (Apple वा Google) ले आफ्नै सर्तअनुसार तपाईंको बोली प्रशोधन गर्न सक्छ।',
        body3: 'Clickt ले बोल्ने व्यक्ति पहिचान गर्दैन, पृष्ठभूमिमा रेकर्ड गर्दैन, र फोन कल वा सिस्टम अडियो कैद गर्दैन। रेकर्ड गरिने व्यक्तिहरूलाई जानकारी दिने र तपाईंमा लागू हुने रेकर्डिङ कानूनको पालना गर्ने जिम्मेवारी तपाईंको हो।',
      },
      section4: { bodyNotes: 'Notes मा “AI ले बनाउनुहोस्” र “काम निकाल्नुहोस्” ले तपाईंले पठाउन रोजेको नोटको पाठ, विषय वा निर्देशन मात्र, तपाईंले अनुरोध गर्दा मात्र पठाउँछन्। नतिजा ड्राफ्ट हुन्। तपाईंले समीक्षा गरेर पुष्टि नगरेसम्म केही सुरक्षित हुँदैन, र कुनै Checklist वस्तु वा Teams रेकर्ड बनाइँदैन।' },
    },
    terms: {
      section4: {
        body1: 'Clickt मा तपाईंले सिर्जना गर्ने सामग्री - तपाईंका कार्यहरू, नोटहरू, चेकलिस्टहरू, Builder डेटासेटहरू, र Presentation डेकहरू ("तपाईंको सामग्री") - को स्वामित्व तपाईंको हुन्छ। तपाईं Clickt लाई सेवा उपलब्ध गराउने र सहयोग गर्ने उद्देश्यले मात्र तपाईंको सामग्री होस्ट, प्रशोधन, प्रसारण, र ब्याकअप गर्ने सीमित अनुमति दिनुहुन्छ, जसमा हाम्रो <a href="privacy.html">गोपनीयता विवरण</a> मा वर्णन गरिएअनुसार तपाईंले ClicktAI Copilot वा Notes भित्रको AI सँग सहयोग माग्दा सम्बन्धित सामग्री AI प्रदायकलाई पठाउने कुरा पनि समावेश छ।',
        bodyRecording: 'तपाईंले Notes मा “बैठक रेकर्ड” प्रयोग गर्नुभयो भने रेकर्ड गरिने सबैलाई जानकारी दिने, लागू कानूनले माग्ने सहमति लिने, र तपाईं तथा सहभागीहरू रहेको ठाउँको रेकर्डिङ र गोपनीयता कानूनको पालना गर्ने जिम्मेवारी पूर्ण रूपमा तपाईंको हो। जानकारी नपाएका वा आपत्ति जनाएका व्यक्तिलाई रेकर्ड नगर्नुहोस्। Clickt ले रेकर्डिङ र ट्रान्सक्रिप्सनका उपकरण उपलब्ध गराउँछ तर तपाईंले तिनको प्रयोग कसरी गर्नुहुन्छ भन्नेमा जिम्मेवार हुँदैन।',
      },
      section5: { bodyNotes: 'Notes भित्रको AI - “AI ले बनाउनुहोस्”, “काम निकाल्नुहोस्” र बैठक सारांश - ले पनि यसरी नै काम गर्छ। यसले तपाईंले समीक्षा गर्नका लागि ड्राफ्ट बनाउँछ, र यी सर्तहरू त्यसमा उसैगरी लागू हुन्छन्।' },
      section6: { bodyNotes: 'Notes भित्रको AI मा पनि यही लागू हुन्छ। बैठकको ट्रान्सक्रिप्सनले तपाईंको उपकरणमै बनेको स्पिच रिकग्निसन सेवा पनि प्रयोग गर्छ, जुन Apple वा Google ले उपलब्ध गराउँछन् र तिनका सर्तले चल्छ। त्यो सेवाको जिम्मेवारी Clickt को होइन।' },
    },
    security: {
      dataInfra: {
        notes: { q: 'Notes कहाँ भण्डारण गरिन्छ?', a: 'प्रयोगकर्ताको उपकरणमा, उनको खाताको निजी भण्डारणमा। नोट, फोल्डर र बैठकका ट्रान्सक्रिप्ट Clickt को क्लाउडमा अपलोड गरिँदैनन्, त्यसैले उपकरणहरूबीच सिंक हुँदैनन्। प्रयोगकर्ताले अगाडि पठाएपछि मात्र नोटबाट केही बाहिर जान्छ: पुष्टि गरिएको Checklist वस्तु, Teams कार्य, निमन्त्रणा वा घोषणा, वा AI प्रदायकलाई पठाइएको पाठ।' },
        meetings: { q: 'बैठकको रेकर्डिङलाई के हुन्छ?', a: 'सहमति सूचना स्वीकार गरेपछि, रेकर्डिङ स्क्रिन खुला रहँदा मात्र रेकर्डिङ चल्छ। अडियो अस्थायी निजी फाइलमा जान्छ र ट्रान्सक्रिप्ट सुरक्षित भएपछि वा रेकर्डिङ रद्द भएपछि मेटिन्छ। Clickt ले कच्चा अडियो आफ्ना सर्भरमा अपलोड गर्दैन। उपकरणको स्पिच रिकग्निसन सेवा (Apple वा Google) ले बोली प्रशोधन गर्न सक्छ। Clickt ले बोल्ने व्यक्ति पहिचान, पृष्ठभूमि रेकर्डिङ वा कल कैद गर्दैन।' },
      },
      ai: { providers: { a: 'तपाईंले काम गरिरहनुभएको मोड्युलबाट विशेष अनुरोधसँग सम्बन्धित सामग्री मात्र - तपाईंको सम्पूर्ण कार्यक्षेत्र कहिल्यै होइन। Notes मा, “AI ले बनाउनुहोस्” वा “काम निकाल्नुहोस्” का लागि प्रयोगकर्ताले पठाउन रोजेको पाठ मात्र। Free मा, तपाईं आफ्नै प्रदायक कुञ्जी जडान गर्नुहुन्छ। Business मा, तपाईंको एडमिनले Clickt-अनुमोदित प्रदायक तोक्छ।' } },
    },
    industryPages: {
      common: { notesLabel: 'व्यवहारमा Notes', notesTitle: 'बैठकमा भनिएको कुरालाई जिम्मेवार काममा बदल्नुहोस्।', notesLead: 'Notes हरेक टोलीका लागि उस्तै चल्छ। फरक पर्ने बैठक मात्र हो।', notesB1: 'फेरि टाइप नगरी समात्नुहोस्', notesB1Body: 'बैठक लेख्नुहोस्, बोल्नुहोस् वा रेकर्ड गर्नुहोस्। पछि कार्य बुँदा सूचीमा सार्नु पर्दैन।', notesB2: 'काम उपयुक्त ठाउँमा पठाउनुहोस्', notesB2Body: 'हरेक फलो-अप तपाईंको Checklist वा तपाईंले चलाउने टोलीमा जान्छ।', notesB3: 'केही बन्नुअघि समीक्षा', notesB3Body: 'हरेक ड्राफ्ट पहिले व्यक्तिले जाँच्छ। नोट तपाईंको उपकरणमै रहन्छन्।' },
      schools: { notesRole: 'प्रधानाध्यापक, विभागप्रमुख र प्रशासक', notes: 'कर्मचारी वा परीक्षा-योजना बैठक रेकर्ड गर्नुहोस्, फलो-अप निकाल्नुहोस्, र हरेकलाई उपयुक्त व्यक्ति वा आफ्नै Checklist मा पठाउनुहोस्।', notesScenario: 'कर्मचारी बैठकपछि विभागप्रमुखले नोट रेकर्ड वा टाइप गर्छन्। “काम निकाल्नुहोस्” ले हल बुक गर्ने, प्रश्नपत्र छाप्ने र निरीक्षक पक्का गर्ने जस्ता कार्य सूचीबद्ध गर्छ, र हरेक कार्य Teams मा जिम्मेवार व्यक्ति वा प्रमुखको आफ्नै Checklist मा जान्छ।' },
      healthcare: { notesRole: 'सञ्चालन, सुविधा र नर्सिङ प्रशासक', notes: 'गैर-क्लिनिकल सिफ्ट हस्तान्तरण र मर्मत बैठक समात्नुहोस्, र फलो-अपलाई जिम्मेवार कार्यमा बदल्नुहोस्।', notesScenario: 'सुविधा प्रबन्धकले उपकरण जाँच र कोठा तयारीबारे हस्तान्तरण बैठकको नोट राख्छन्। “काम निकाल्नुहोस्” ले फलो-अपलाई अर्को सिफ्टका कार्य बनाउँछ। Notes गैर-क्लिनिकल समन्वयका लागि मात्र प्रयोग गर्नुहोस्, बिरामीको जानकारीका लागि कहिल्यै होइन।' },
      banks: { notesRole: 'शाखा प्रबन्धक र सञ्चालन टोली', notes: 'शाखाको तयारी र व्यवस्थापन बैठकलाई फेरि टाइप नगरी जिम्मेवार फलो-अपमा बदल्नुहोस्।', notesScenario: 'शाखा प्रबन्धकले साप्ताहिक तयारी बैठक लेख्छन्। “काम निकाल्नुहोस्” ले कर्मचारी व्यवस्था, साइनेज र तालिम पुनःताजगी जस्ता कार्य सूचीबद्ध गर्छ, र हरेक Teams मा तोकिन्छ वा प्रबन्धकको Checklist मा रहन्छ। Notes आन्तरिक समन्वयमा मात्र राख्नुहोस्, ग्राहकको खाता विवरणमा होइन।' },
      ngos: { notesRole: 'कार्यक्रम अधिकृत र क्षेत्र समन्वयकर्ता', notes: 'क्षेत्र भ्रमण र साझेदार बैठक समात्नुहोस्, अनि सहमत भएका कार्यलाई टोलीका फलो-अपमा बदल्नुहोस्।', notesScenario: 'क्षेत्र भ्रमणपछि कार्यक्रम अधिकृतले डिब्रिफ रेकर्ड गर्छन्। “काम निकाल्नुहोस्” ले उपस्थिति प्रतिवेदन पठाउने र अर्को वितरण पक्का गर्ने जस्ता फलो-अप सूचीबद्ध गर्छ, र हरेकलाई उपयुक्त व्यक्ति वा आफ्नै Checklist मा पठाउँछ।' },
      hotels: { notesRole: 'महाप्रबन्धक र विभागप्रमुख', notes: 'दैनिक ब्रिफिङ र सेवा-सुधार बैठक लेख्नुहोस्, र फलो-अप उपयुक्त सिफ्टमा पठाउनुहोस्।', notesScenario: 'ड्युटी प्रबन्धकले बिहानको ब्रिफिङ रेकर्ड गर्छन्। “काम निकाल्नुहोस्” ले कोठाको खराबी मर्मत, लाउन्ज पुनःभर्ने र पाहुनालाई फिर्ता कल गर्ने जस्ता कार्य छुट्ट्याउँछ, र Teams मा उपयुक्त विभागलाई तोक्छ।' },
      restaurants: { notesRole: 'मालिक र सिफ्ट प्रबन्धक', notes: 'सिफ्टअघिको ब्रिफिङ र बन्द गर्दाको नोट समात्नुहोस्, र भनिएको कुरालाई तोकिएका कार्यमा बदल्नुहोस्।', notesScenario: 'सिफ्ट प्रबन्धकले बन्द गर्दाको नोट बोलेर राख्छन्। “काम निकाल्नुहोस्” ले सामग्री फेरि मगाउने, फ्रायर मर्मत गर्ने र विशेष मेनु बोर्ड अद्यावधिक गर्ने जस्ता फलो-अप सूचीबद्ध गर्छ, र हरेक जिम्मेवार व्यक्तिमा जान्छ।' },
      construction: { notesRole: 'साइट इन्जिनियर र परियोजना प्रबन्धक', notes: 'साइट बैठक र स्न्याग वाक रेकर्ड गर्नुहोस्, र सहमत हरेक कार्यलाई जिम्मेवार कार्यमा बदल्नुहोस्।', notesScenario: 'साइट बैठकपछि परियोजना प्रबन्धकले छलफल रेकर्ड गर्छन्। “काम निकाल्नुहोस्” ले सामग्री आइपुग्ने पुष्टि, ढलान पुनः जाँच र स्न्याग बन्द गर्ने जस्ता कार्य सूचीबद्ध गर्छ, र हरेकलाई Teams मा उपयुक्त फोरम्यान वा सुपरभाइजरमा पठाउँछ।' },
    },
    clicktai: { benefits: { oneBody: 'एउटै अनुरोधले Teams, Checklist, Builder र Presentation मा अलग-अलग दोहोर्याएर बनाउनुपर्ने काम जोड्न सक्छ। Notes ले उही AI की प्रयोग गरेर नोट ड्राफ्ट गर्छ र काम निकाल्छ।' } },
  },
};
