// Copy added for the product pages (Teams, Checklist, Builder, Presentation, ClicktAI).
// Most product copy is reused from the existing modulePages / clicktai dictionaries.
export default {
  en: {
    prod: {
      release: 'iPhone, iPad and Mac on the App Store · Android in private testing',
      crumbProduct: 'Product',
      seeKicker: 'See it work',
      aiKicker: 'ClicktAI',
      seeTeams: { title: 'Try the ownership rules.', lead: 'Claim a task, race two teammates for it, and watch reminders arrange themselves around the night.' },
      seeChecklist: { title: 'Tick it off. It comes <em>back.</em>', lead: 'A recurring checklist finishes, then returns next cycle with the same steps every time. Try it.' },
      seeBuilder: { title: 'One dataset, twelve ways to <em>see</em> it.', lead: 'Switch the chart and the answer changes shape. Builder offers twelve chart types, from bar and line to box plot and heatmap.' },
      seePresentation: { title: 'Restyle the whole deck in <em>one tap.</em>', lead: 'Pick a designed theme and every slide follows. Clickt ships 23 built-in themes, plus designed families such as Spotlight, Guided Story and Editorial.' },
      caption: 'Screens from the Clickt app',
      startTitle: 'Start with the work in front of you.',
      ai: {
        title: 'One assistant in every <em>module.</em>',
        lead: 'Teams, Checklist, Builder and Presentation each have a copilot that knows the module it lives in, and the ClicktAI assistant on the home screen works across all of them.',
        tryIt: 'Try it yourself',
        cTeams: 'Teams Copilot',
        cTeamsB: 'Plan the team, invites and announcements from one request.',
        cChecklist: 'Checklist Copilot',
        cChecklistB: 'Turn a goal or a file into a checklist you can preview.',
        cBuilder: 'Analysis Copilot',
        cBuilderB: 'Ask for the best analysis for the columns you selected.',
        cPresentation: 'Slide Copilot',
        cPresentationB: 'Draft a whole deck with optional web research and AI visuals, or improve the slide you are on.',
        cConnect: 'Connect a provider',
        cConnectB: 'Bring your own OpenAI, Anthropic, Gemini or NVIDIA key.',
        rulesKicker: 'The rules it follows',
        rulesTitle: 'Built to be <em>trusted</em> with your work.',
        r1t: 'Preview before any write',
        r1b: 'Every change shows what will happen and waits for your approval.',
        r2t: 'A clear no, with alternatives',
        r2b: 'Unsupported requests get one sentence, one reason and safer options.',
        r3t: 'It asks when unsure',
        r3b: 'If two things share a name, it asks which you mean instead of guessing.',
        r4t: 'Roles are respected',
        r4b: 'It works within the permissions your team role already gives you.',
      },
    },
  },
  ne: {
    prod: {
      release: 'App Store मा iPhone, iPad र Mac · Android निजी परीक्षणमा',
      crumbProduct: 'उत्पादन',
      seeKicker: 'काम गरेको हेर्नुहोस्',
      aiKicker: 'ClicktAI',
      seeTeams: { title: 'जिम्मेवारीका नियम आफैँ प्रयोग गरेर हेर्नुहोस्।', lead: 'कार्य दाबी गर्नुहोस्, दुई सहकर्मीलाई प्रतिस्पर्धा गराउनुहोस्, र रिमाइन्डरहरू रातको समय बचाएर कसरी मिल्छन् हेर्नुहोस्।' },
      seeChecklist: { title: 'टिक लगाउनुहोस्। यो फेरि <em>आउँछ।</em>', lead: 'दोहोरिने चेकलिस्ट सकिन्छ, अनि अर्को चक्रमा उही चरणसहित फर्कन्छ। आफैँ प्रयोग गर्नुहोस्।' },
      seeBuilder: { title: 'एउटै डेटासेट, हेर्ने <em>बाह्र</em> तरिका।', lead: 'चार्ट बदल्नुहोस् र उत्तरको स्वरूप फेरिन्छ। Builder ले बार र लाइनदेखि बक्स प्लट र हिटम्यापसम्म बाह्र चार्ट प्रकार दिन्छ।' },
      seePresentation: { title: 'पूरै डेकलाई <em>एक ट्यापमै</em> नयाँ रूप दिनुहोस्।', lead: 'डिजाइन गरिएको थिम रोज्नुहोस् र हरेक स्लाइड पछ्याउँछ। Clickt मा २३ समावेश गरिएका थिम, साथै Spotlight, Guided Story र Editorial जस्ता डिजाइन गरिएका परिवारहरू छन्।' },
      caption: 'Clickt एपका स्क्रिनहरू',
      startTitle: 'तपाईंको अगाडि रहेको कामबाट सुरु गर्नुहोस्।',
      ai: {
        title: 'हरेक <em>मोड्युलमा</em> एउटै सहायक।',
        lead: 'Teams, Checklist, Builder र Presentation हरेकमा आफू बस्ने मोड्युल चिन्ने कोपाइलट छ, र गृहपृष्ठको ClicktAI सहायकले सबैमा काम गर्छ।',
        tryIt: 'आफैँ प्रयोग गर्नुहोस्',
        cTeams: 'Teams कोपाइलट',
        cTeamsB: 'एउटै अनुरोधबाट टोली, निमन्त्रणा र घोषणाको योजना बनाउनुहोस्।',
        cChecklist: 'Checklist कोपाइलट',
        cChecklistB: 'लक्ष्य वा फाइललाई पूर्वावलोकन गर्न मिल्ने चेकलिस्टमा बदल्नुहोस्।',
        cBuilder: 'विश्लेषण कोपाइलट',
        cBuilderB: 'तपाईंले रोजेका स्तम्भका लागि उत्तम विश्लेषण माग्नुहोस्।',
        cPresentation: 'स्लाइड कोपाइलट',
        cPresentationB: 'वैकल्पिक वेब अनुसन्धान र AI दृश्यसहित पूरै डेक ड्राफ्ट गर्नुहोस्, वा तपाईं रहेको स्लाइड सुधार्नुहोस्।',
        cConnect: 'प्रदायक जोड्नुहोस्',
        cConnectB: 'आफ्नै OpenAI, Anthropic, Gemini वा NVIDIA की ल्याउनुहोस्।',
        rulesKicker: 'यसले पालना गर्ने नियम',
        rulesTitle: 'तपाईंको कामको लागि <em>भरपर्दो</em> बनाइएको।',
        r1t: 'कुनै पनि लेख्नुअघि पूर्वावलोकन',
        r1b: 'हरेक परिवर्तनले के हुनेछ देखाउँछ र तपाईंको स्वीकृतिको प्रतीक्षा गर्छ।',
        r2t: 'विकल्पसहित स्पष्ट “होइन”',
        r2b: 'असमर्थित अनुरोधले एउटा वाक्य, एउटा कारण र सुरक्षित विकल्पहरू पाउँछ।',
        r3t: 'शंका लाग्दा सोध्छ',
        r3b: 'दुई कुराको नाम उस्तै भए अनुमान नगरी तपाईंको मतलब कुन हो सोध्छ।',
        r4t: 'भूमिकाको सम्मान गर्छ',
        r4b: 'तपाईंको टोलीको भूमिकाले पहिल्यै दिएको अनुमति भित्र रहेर काम गर्छ।',
      },
    },
  },
};
